### ISSUE TITLE
Compilation error for LPC1768

### ISSUE THREAD

**Issue by minoger** [bigtreetech/BIGTREETECH-SKR-V1.3#102]
**i got the following error while compiling:**

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/nxplpc-arduino-lpc176x/nxp_lpc1768.html
PLATFORM: NXP Arduino LPC176x 0.0.2 > NXP LPC1768

HARDWARE: LPC1768 100MHz, 31.80KB RAM, 464KB Flash
DEBUG: Current (cmsis-dap) On-board (cmsis-dap) External (blackmagic, jlink)
PACKAGES: toolchain-gccarmnoneeabi 1.80201.190214 (8.2.1), framework-arduino-lpc176x 0.1.3
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ off, Compatibility ~ strict
Found 4 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Servo> 1.0.0
|-- <LiquidCrystal> 1.0.0
|-- <U8glib-HAL> 0.4
|-- <TMCStepper> 0.4.5
  File "C:\Users\michael.richter\Downloads\3dThings\SKR\13\BIGTREETECH-SKR-V1.3-master\BIGTREETECH-SKR-V1.3-master\firmware\Marlin-bugfix-2.0.x\Marlin\src\HAL\HAL_LPC1768\upload_extra_script.py"
, line 16
 
    print '\nUnable to find destination disk (' + e + ')\n' \
 
                                              ^
 
SyntaxError: invalid syntax

**Please help me solve this issue**

**Comment by chaoticchoas** [comment]
This seems like a simple syntax error with python. Make sure to have the latest python 3 installed and update platformio.
