### ISSUE TITLE
There are no resistors on any gate of power MOSFETs

### ISSUE THREAD

**Issue by ElectroAaron** [bigtreetech/BIGTREETECH-SKR-V1.3#113]
Driving directly power MOSFETs from MC74HCT125A without limiting resistors may damage the chip. A closer look at the [datasheet](https://www.onsemi.com/pub/Collateral/MC74HCT125A-D.PDF), reveals that maximum output current is ±35mA for each buffer output pin.

**Comment by karabas2011** [comment]
So what conditions cause possible fail?

**Comment by Pixel-Soup** [comment]
It shouldn't be an issue.  The fet gate looks like a capacitor to the driver whose ON resistance will limit the peak current during each pwm cycle.

**Comment by ElectroAaron** [comment]
Yeah sure! It does make sense, I wasn't taking into account the own internal RDSon of the MC74HCT125A. Sorry for my mistake. Issue is close.
