### ISSUE TITLE
Driver Error: 8 Printer Halted TMC5160

### ISSUE THREAD

**Issue by thezak48** [bigtreetech/BIGTREETECH-SKR-V1.3#117]
Just installed the board on my Ender 3 and uploaded the new firmware and now I get this error everytime I try to turn on the printer Driver Error: 8 Printer Halted  I am using TMC5160

**Comment by loudthunder** [comment]
Same

**Comment by thezak48** [comment]
@loudthunder here follow this, it has resolved my issue https://github.com/MarlinFirmware/Marlin/issues/15296
