### ISSUE TITLE
DRV8825 not working on SKR1.3 for 1 driver(E0)

### ISSUE THREAD

**Issue by legojedidev** [bigtreetech/BIGTREETECH-SKR-V1.3#119]
So I use an Anet a8 but recently my board caught on fire. I decided to upgrade to an SKR 1.3 and bought 5 drv8825 stepper drivers. Everything works fine except for my E0(E1 is being used for my other z-axis). My E0 motor gets current, but it barely moves. Any idea why this may be happening? I am running Marlin 2.0 and can upload my configuration files later. Also I can't get my LCD 2004 to work. Any help is appreciated!

**Comment by Tomthi** [comment]
Have you tried adjusting the vREF for that stepper driver? They may be set too low. I had issues with the voltages and after adjusting them performance was much better.

**Comment by legojedidev** [comment]
I just figured out that the driver itself was causing a short

**Comment by erberru70** [comment]
> Así que uso un Anet a8 pero recientemente mi placa se incendió. Decidí actualizarme a un SKR 1.3 y compré 5 controladores paso a paso drv8825. Todo funciona bien, excepto mi E0 (E1 se está utilizando para mi otro eje z). Mi motor E0 recibe corriente, pero apenas se mueve. ¿Alguna idea de por qué esto puede estar sucediendo? Estoy ejecutando Marlin 2.0 y puedo cargar mis archivos de configuración más tarde. Además, no puedo hacer que mi LCD 2004 funcione. Cualquier ayuda es apreciada!

hola , como conseguiste cargar marlin 2.0 en la placa skr v1.3, por que a mi no para de darme error al compilar marlin con vscode
