### ISSUE TITLE
SKR1.3 + smoothieware + lcd

### ISSUE THREAD

**Issue by sancrum** [bigtreetech/BIGTREETECH-SKR-V1.3#12]
Hi
I have RepRapDiscount full graphics smart display.
How can I use it with SKR + smoothiware?

**Comment by Msq001** [comment]
The SPI interface of `RepRapDiscount full graphics smart display` in smoothieware must be hardware SPI, but it's software spi wiring in SKR V1.3,   so if you want use smoothieware, you can only use extra wiring to share the SPI of the SD card for LCD

**Comment by ShohninDmitriy** [comment]
![b29136c6ae6cd6a803ec209aa9a9813e](https://user-images.githubusercontent.com/20542738/56341240-12955300-61bd-11e9-99f2-9437a5ad2b17.jpg)
![852f096d61f1da88b86a3d3ac8f87e8e](https://user-images.githubusercontent.com/20542738/56341250-17f29d80-61bd-11e9-9fa1-e608726c761b.jpg)

**Comment by Filcanna** [comment]
So you’re saying we need a custom cable to connect RRDGLCD on SKR v 1.3?

**Comment by sancrum** [comment]
Yep.
Thank you guys!

**Comment by Filcanna** [comment]
Well. My 1.3 board arrived with Marlin, but no menus. So I’m trying LCD on SmoothieWare (it works PERFECTLY with its cables, twisted, on a Sbase I own), but with SKR board on display there is only light, other functionalities are fine. Well, I’ll try DuPont bifemale cables ASAP.
