### ISSUE TITLE
Error: 'LPC176x' has not been declared

### ISSUE THREAD

**Issue by dvdsouza** [bigtreetech/BIGTREETECH-SKR-V1.3#130]
We are trying to compile the firmware, but we are receiving the following errors:

![image](https://user-images.githubusercontent.com/5842083/68950678-6a1f8f80-079b-11ea-90f9-5a45848898c1.png)
![image](https://user-images.githubusercontent.com/5842083/68950680-6d1a8000-079b-11ea-825a-0ed34ebbff68.png)
![image](https://user-images.githubusercontent.com/5842083/68950682-6ee44380-079b-11ea-9987-686d036a089a.png)

Does Anyone Have a Clue about this problem?

**Comment by Redssnake77** [comment]
Have you set your board type in the platform.io file? it towards the bottom, beneath your marlin files. Have you watched TeachingTech's YouTube video?

**Comment by ursoft** [comment]
Cause: https://github.com/teemuatlut/TMCStepper/commit/a9187feee034c97ec292cf916d3a12d100774b0d

**Comment by ursoft** [comment]
To avoid cause, you can use lower `TMCStepper@>=0.5.2,<0.6.0` as in original Marlin

**Comment by BugfixXxX** [comment]
Hi guys, I am getting the same errors, I think it occures after I updatet the TMCStepper library but I also tried to lower the version which sadly doesn´t have any affect.
Does anyone have another solution?

**Comment by dvdsouza** [comment]
@ursoft 

We have tried to change the version:
`TMCStepper@>=0.5.2,<0.6.0`
also the current bugfix 2.0 version:
`TMCStepper@>=0.5.0,<1.0.0` 

It makes sense, but we get the same error.
Another idea?

**Comment by ursoft** [comment]
> @ursoft
> 
> We have tried to change the version:
> `TMCStepper@>=0.5.2,<0.6.0`
you should also delete ...\firmware\Marlin-bugfix-2.0.x\.pio\libdeps\LPC1768\TMCStepper* folder

**Comment by Al9900** [comment]
Hi guys, i have your same problem but i've just solved... TMC stepper V.6.0.1 has been released 1 days ago and V.0.6.1, 6 days ago and both two create errors... Every time you compile the firmware , it'll always download the latest version and if you unistall TMC_stepper in platoformio libraries , Marlin will provide to reinstall it while compiling... The only way to get out is to download TMC_stepper 0.5 and put manually this  librarie inside Platoformio folder in USERS. 

Now i got 0 errors and it work to me, hope it'll help you.
 Fell free to contact me if was not clear. 

Cheers.

**Comment by dvdsouza** [comment]
@Al9900 
It worked!
The problem is the version 0.6.x.
We have changed the platformio.ini with the version 0.5.2 `TMCStepper@>=0.5.2,<0.5.3`, and it worked like a charm.

I am closing the issue. Thanks.

**Comment by dvdsouza** [comment]
The problem is the TMCStepper version 0.6.x.
We have changed the platformio.ini with the version 0.5.2 TMCStepper@>=0.5.2,<0.5.3

**Comment by redeyejoe** [comment]
I installed .5.2 and changed the lib_dep to the TMCStepper@>=0.5.2,<0.5.3 in platform.ini  saved, but when compiling it still says it using |-- <TMCStepper> 0.6.1 and wont compile.

**Comment by dolfelt** [comment]
@redeyejoe Make sure to update the dependency in the `[env:LPC1768]` section (further down the file)

**Comment by KuraiKitsune** [comment]
> @redeyejoe Make sure to update the dependency in the `[env:LPC1768]` section (further down the file)

That was my missing part. All good now!
Many thanks, contributors!

**Comment by redeyejoe** [comment]
Yes, thanks. That did it

**Comment by suckmo** [comment]
![image](https://user-images.githubusercontent.com/61891988/76130757-fa4b4400-5fd9-11ea-844f-3912649198f0.png)
![image](https://user-images.githubusercontent.com/61891988/76130766-03d4ac00-5fda-11ea-94db-e52a24e33214.png)
![image](https://user-images.githubusercontent.com/61891988/76130775-0b945080-5fda-11ea-883c-0c755f43f3b1.png)
![image](https://user-images.githubusercontent.com/61891988/76130792-1949d600-5fda-11ea-8a41-d4c692c1541b.png)
Alright guys, Ive changed the ini file to call TMC 0.5.2 as you can see from the attachments. And it confirms in the lib dependecy that its calling the correct version, but its still failing.... any other suggestions???

**Comment by enry68** [comment]
> 
> 
> Hi guys, i have your same problem but i've just solved... TMC stepper V.6.0.1 has been released 1 days ago and V.0.6.1, 6 days ago and both two create errors... Every time you compile the firmware , it'll always download the latest version and if you unistall TMC_stepper in platoformio libraries , Marlin will provide to reinstall it while compiling... The only way to get out is to download TMC_stepper 0.5 and put manually this librarie inside Platoformio folder in USERS.
> 
> Now i got 0 errors and it work to me, hope it'll help you.
> Fell free to contact me if was not clear.
> 
> Cheers.

Thank you very much!!! I've solved installing manually the TMClibrary V.5.0. Thank you

**Comment by ltmhenrique** [comment]
> Olá pessoal, tenho o mesmo problema, mas acabei de resolver ... O TMC stepper V.6.0.1 foi lançado há 1 dia e V.0.6.1, 6 dias atrás e os dois criam erros ... Sempre você compila o firmware, ele sempre baixa a versão mais recente e se você desinstalar o TMC_stepper nas bibliotecas platoformio, o Marlin fornecerá a reinstalação durante a compilação ... A única maneira de sair é fazer o download do TMC_stepper 0.5 e colocar manualmente essa biblioteca Pasta Platoformio em USUÁRIOS.
> 
> Agora eu tenho 0 erros e funciona para mim, espero que ajude você.
> Não hesite em contactar-me se não estiver claro.
> 
> Felicidades.

you could show more step by step how to do this, i'm a layman i'm struggling to solve this problem.

> Olá pessoal, tenho o mesmo problema, mas acabei de resolver ... O TMC stepper V.6.0.1 foi lançado há 1 dia e V.0.6.1, 6 dias atrás e os dois criam erros ... Sempre você compila o firmware, ele sempre baixa a versão mais recente e se você desinstalar o TMC_stepper nas bibliotecas platoformio, o Marlin fornecerá a reinstalação durante a compilação ... A única maneira de sair é fazer o download do TMC_stepper 0.5 e colocar manualmente essa biblioteca Pasta Platoformio em USUÁRIOS.
> 
> Agora eu tenho 0 erros e funciona para mim, espero que ajude você.
> Não hesite em contactar-me se não estiver claro.
> 
> Felicidades.

you could show more step by step how to do this, i'm a layman i'm struggling to solve this problem?

**Comment by ltmhenrique** [comment]
> Hi guys, i have your same problem but i've just solved... TMC stepper V.6.0.1 has been released 1 days ago and V.0.6.1, 6 days ago and both two create errors... Every time you compile the firmware , it'll always download the latest version and if you unistall TMC_stepper in platoformio libraries , Marlin will provide to reinstall it while compiling... The only way to get out is to download TMC_stepper 0.5 and put manually this librarie inside Platoformio folder in USERS.
> 
> Now i got 0 errors and it work to me, hope it'll help you.
> Fell free to contact me if was not clear.
> 
> Cheers.

you could show more step by step how to do this, i'm a layman i'm struggling to solve this problem?

**Comment by Ozista** [comment]
Hi, Guys, I got this solved today without being able to download, but TMC_stepper 0.5.2 was installed in "Platform-Libraries-TMCstepper by tee..." anyway. 
I have replaced 4 occurrences of TMCStepper@>=.... to  "TMCStepper@>=0.5.2,<0.6.0"  in Platformio.ini.
This was my breakthrough.

Thank you all !!!
