### ISSUE TITLE
Z_Min always triggered (

### ISSUE THREAD

**Issue by fineobjetcs** [bigtreetech/BIGTREETECH-SKR-V1.3#146]
Hi ! I have this issue
At start all be ok! Z_Min works as Z_Probe fine, but three days ago Z_Min starts always triggered. I try to change firmware (Marlin20bugfix, smoothiware), change settings(invert ZMIN Probe etc), play with pullup, but nothing happens, i try this with and without wires and sensor.
What wrong ? May it be electrical error ? How i check the PIN directly ? Maybe from arduino IDE ? With simple code ? PIN 1_25 is analog or digital ?

**Comment by fxh1357** [comment]
"Three days ago" sounds like a limit switch connected as normally closed, thus a broken wire or disconnected switch would result in a 'TRIGGERED' state

**Comment by oldman4U** [comment]
Close this ticket or reply.
