### ISSUE TITLE
SKR 1.3 with MKS2208 v1.1 TMC Connection Error (UART)

### ISSUE THREAD

**Issue by Brainc0re** [bigtreetech/BIGTREETECH-SKR-V1.3#15]
I got my board today. For testing, i connected one stepper (Z). according to the manual i removed all jumpers from the STEP/DIR headers and set them on the UART headers. But i always get a TMC CONNECTION ERROR on the display...

This is may current build:
https://drive.google.com/file/d/1NryYj-VFD_dcWFG64mShB-L8xsBiXHr1/view?usp=sharing

**Comment by doggyfan** [comment]
I had this and found out the problem was today.

On the TMC2208 driver board you need to solder the PDN to the N.C pin next to it. The serial connection will then be correct.

![Dsc00107](https://user-images.githubusercontent.com/49303635/56390484-08f30600-6224-11e9-83c3-83802f8b9252.jpg)

![Dsc00109](https://user-images.githubusercontent.com/49303635/56390490-0db7ba00-6224-11e9-8f95-5870558c4bde.jpg)

**Comment by Brainc0re** [comment]
Okay. I will try it in ~20 minutes. Thank you

**Comment by Brainc0re** [comment]
Nope. Still "TMC Connection Error" on the screen

**Comment by doggyfan** [comment]
Have you also soldered the UART pad option on your TMC2208 board ?

**Comment by Brainc0re** [comment]
The board has separate jumpers for UART

https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/SKR%20V1.3-Instructions.pdf Site 5/6

**Comment by doggyfan** [comment]
I highly recommend using the protection diodes on each driver board to protect them from back EMF etc.

[https://www.aliexpress.com/item/5PCS-Ultra-Silent-Protector-Stepper-Motor-Driver-Motherboard-Plug-type-Silent-Stepper-For-3D-Printer-Driver/32864664427.html](url)

**Comment by doggyfan** [comment]
Also, comment out this line on the configuration_adv.h file ..

`
//#define SOFTWARE_DRIVER_ENABLE
`

**Comment by Brainc0re** [comment]
> Also, comment out this line in your configuration_adv.h file ..
> 
> `//#define SOFTWARE_DRIVER_ENABLE`

If i define that, error still there and i cant control the stepper via "move axis Z" anymore

**Comment by PapeJelly** [comment]
Check out their instructional video which also includes TMC2208 setup

**https://www.youtube.com/watch?v=oaXfXkPYHpw**

**Comment by Brainc0re** [comment]
> Check out their instructional video which also includes TMC2208 setup
> 
> [](**https://www.youtube.com/watch?v=oaXfXkPYHpw**)

With the help from Vanessa_E, author of [TMC2208 UART on BigTreeTech/BIQU SKR V1.1 and V1.3 Controllers](https://www.instructables.com/id/TMC2208-UART-on-BigTreeTechBIQU-SKR-V11-and-V13-Co/), we found out, that my MKS Drivers are not able to communicate via UART. I need some Fyetc v1.2 or TMC2208 drivers from Eryone.

**Comment by doggyfan** [comment]
That's not true, I'm using them just fine with the extra soldered connection.

**Comment by Brainc0re** [comment]
I dont have solderpads on my Stepper drivers and soldering the to pins in the middle has the same function as the jumper on the board.

![2208pin](https://user-images.githubusercontent.com/21007884/56455700-17dfd280-6362-11e9-8523-fe81ef3054c6.jpg)

**Comment by doggyfan** [comment]
Can you not solder a thin wire from the chips UART pin to the N.C pin ?
It's a bit tiny but easy enough to do under a good magnifying glass.

**Comment by Brainc0re** [comment]
Vanessa_E made this suggestion too. I have so many tools and stuff, but no magnification/microscope and such thin wire. According to the datasheet from trinamic, the solder pads are 0.25mm wide and have a pitch of 0.5mm. Thats too small for me for soldering. I will order some v1.2 which have UART.
