### ISSUE TITLE
MMU2

### ISSUE THREAD

**Issue by Sjoerrdd** [bigtreetech/BIGTREETECH-SKR-V1.3#162]
I'm trying to install the MMU2 (Marlin 2.0 supports it), I connected the connector to the TFT port, but can't make it work.
Which serialport is the TFT port? Has someone a solution?

**Comment by Sjoerrdd** [comment]
I think I solved it, it was wired incorrectly. 
I'll try it tomorrow and let you know if it works :)

**Comment by Jays3DAdventure** [comment]
How did you get on? Can you make your firmware available if did get it working please.

Thanks James.

**Comment by Sjoerrdd** [comment]
@Jays3DAdventure https://github.com/Sjoerrdd/Jays3DAdventure
Make sure that you wired it correctly!

If you need help with the wiring, please drop a picture :)

**Comment by Jays3DAdventure** [comment]
Link is 404 :(.

I'll check my wiring, thanks. Can you post a picture of your?

J.

**Comment by Sjoerrdd** [comment]
![20191215_211900](https://user-images.githubusercontent.com/19862992/70868374-9556f380-1f80-11ea-956e-fe252a30a130.jpg)
