### ISSUE TITLE
TMC2208 [TMC CONNECTION ERROR]

### ISSUE THREAD

**Issue by lospo** [bigtreetech/BIGTREETECH-SKR-V1.3#17]
I configured marlin and SKR1.3 to work in uart mode but i have the same message on the display.
The driver are BIGTREETECH TMC2208 SKU:UUU001758
The board is SKR V1.3, i follow the instruction here: https://www.youtube.com/watch?v=oaXfXkPYHpw
But i have the same message on display. 

Attached a photo of my driver.

Here is the output of my M122:
`                X       Y       Z       E
Enabled         false   false   false   false
Set current     800     800     800     800
RMS current     1436    1436   1436     1436
MAX current     2025    2025    2025    2025
Run current     25/31   25/31   25/31   25/31
Hold current    12/31   12/31   12/31   12/31
CS actual       0/31   0/31     0/31    0/31
PWM scale   	0       0       0       0
vsense          0=.325  0=.325  0=.325  0=.325
stealthChop     false   false   false   false
msteps          256      256     256     256
tstep           0       0       0       0
pwm
threshold       0       0       0       0
[mm/s]          -       -       -       -
OT prewarn      false   false   false   false
off time        0       0       0       0
blank time      16      16      16      16
hysteresis
-end            -3      -3     -3       -3
-start          1       1       1       1
Stallguard thrs
DRVSTATUS       X       Y       Z       E
stst
olb
ola
s2gb
s2ga
otpw
ot
157C
150C
143C
120C
s2vsa
s2vsb
Driver registers:
X       0x00:00:00:00    Bad response!
Y      0x00:00:00:00     Bad response!
Z       0x00:00:00:00    Bad response!
E       0x00:00:00:00    Bad response!
Testing X connection... Error: All LOW
Testing Y connection... Error: All LOW
Testing Z connection... Error: All LOW
Testing E connection... Error: All LOW
ok`
![IMG_20190426_161544](https://user-images.githubusercontent.com/12729270/56814283-208f4780-683f-11e9-8909-8fee5e14ab19.jpg)
![IMG_20190426_161555](https://user-images.githubusercontent.com/12729270/56814294-29801900-683f-11e9-9d87-8b108b0b801b.jpg)

**Comment by doggyfan** [comment]
Have you solder bridged the option pads on the TMC2208 driver boards to connect the UART pin on the TMC2208 to the UART driver board pin ?

**Comment by lospo** [comment]
I made no solder, I place jumpers in the board and attached these drivers.
I have no idea of what to solder/connect

**Comment by doggyfan** [comment]
Try soldering these two little pads together on each of your TMC2208 driver boards ..

![TMC2208_SKR_1_3_SOLDER_PADS](https://user-images.githubusercontent.com/49303635/56824156-95697e00-684d-11e9-9f45-fd72168252e4.jpg)

**Comment by lospo** [comment]
I asked also to the supplier, and he give me that image as reference for soldering two pins.
Are the same or i am confused?
![driver](https://user-images.githubusercontent.com/12729270/56825200-cc915c80-6858-11e9-9fea-9da61f3a1674.jpg)

**Comment by doggyfan** [comment]
oh ok, go with what they say. If that doesn't work try the other two pads.

**Comment by lospo** [comment]
Nope, i soldered these pads but the trouble still remain.
And now its difficoult for me de-solder and solder the other two pads.
Do you think i could solder every three pads?
I send photos, please tell me if you see something  wrong. 
![IMG_20190429_191230](https://user-images.githubusercontent.com/12729270/56914928-9c92c500-6ab5-11e9-8075-d5fc133d3430.jpg)
![IMG_20190429_191308](https://user-images.githubusercontent.com/12729270/56914929-9d2b5b80-6ab5-11e9-830a-142d08f8a179.jpg)
![IMG_20190429_191242](https://user-images.githubusercontent.com/12729270/56914930-9d2b5b80-6ab5-11e9-9ed1-38a43c9eeadc.jpg)
![IMG_20190429_191341](https://user-images.githubusercontent.com/12729270/56914931-9d2b5b80-6ab5-11e9-9e25-f1026c017347.jpg)

**Comment by doggyfan** [comment]
You soldered the pads BigTreeTech said to solder. Try soldering the pads I showed you instead.

**Comment by pauleley** [comment]
You need to apply 12 or 24v for it to work

**Comment by pauleley** [comment]
You need to apply 12 or 24v for it to work

**Comment by MrG1981** [comment]
I have the same issue
the jumper on the driver is soldered and works properly with FTDI serial to USB
but not on skr 1.3 board powered by USB or 12v from power supply

**Comment by lospo** [comment]
Hi, i've soldered the pads together (because i have not good skill) and now it works!
Thanks to all of you!

**Comment by doggyfan** [comment]
BigTreeTech are telling people to solder the wrong two pads together :( .. it should be the other two.

**Comment by stricktech** [comment]
hello, i have done the same thing, but i am getting tmc connection error.

i have soldered all 3 pads together, placed on skr 1.3 with the uart jumpers in place.
set firmware to TMC2208 and turned on TMCDEBUG.

i have my board and lcd at work right now, so cant test from 12 volt, powering from usb can give a tmc connection error?

**Comment by lospo** [comment]
Yes, USB power is too low.
You need tre 12/24v power

**Comment by stricktech** [comment]
Ok thanks, I'll reload the firmware and test it from my power supply when I get home.

Just to clarify something I wasent sure about or have heard differing information,

All jumpers should be removed besides uart?
(Black jumpers under driver, and red jumpers to the right side of board)

**Comment by lospo** [comment]
> Ok thanks, I'll reload the firmware and test it from my power supply when I get home.
> 
> Just to clarify something I wasent sure about or have heard differing information,
> 
> All jumpers should be removed besides uart?
> (Black jumpers under driver, and red jumpers to the right side of board)

I removed all, and it works. :D

**Comment by LongLiveCHIEF** [comment]
> BigTreeTech are telling people to solder the wrong two pads together 

No they're not. You can use either combination, or even solder all 3 pads together. You need to be applying the right voltage to the board in order for the the tmc2208 to allow current to flow.  The low voltage from your laptop/PC won't do the trick.

**Comment by Peterg125** [comment]
Same exact problem. I'm replacing my Ender3's main board with SKR v1.3 from bigtreetech. Using 2208 drivers. Have pads soldered, have jumpers on the Uart pins on the board. connected to the 24v powersupply. 
Important note:
My board came with a damaged capacitor on E0, so I switched the pin out defintions for E0 and E1 in code and am simply using E1 port for my extruder. Otherwise everything else is stock.

**Comment by MakerThinking** [comment]
Hello, I have the same problem, I have tried all the options but I still have a tmc connection error on the lcd I have skr board v1.3 and tmc2208 silent stepper
![IMG_20191016_215254](https://user-images.githubusercontent.com/56654519/66954170-26cce680-f060-11e9-8d84-6e182dca69d3.jpg)
![IMG_20191016_215322](https://user-images.githubusercontent.com/56654519/66954171-26cce680-f060-11e9-994e-3b17d3c3d6af.jpg)
![IMG_20191016_215350](https://user-images.githubusercontent.com/56654519/66954172-26cce680-f060-11e9-837f-bd01bb8138e0.jpg)

**Comment by hesham1967** [comment]
I think this has to do with software problem otherwise why I have TMC connection problem with Cura altimaker and Ideamaker but when I use control maker, I don’t have any problem with TMC

**Comment by D4N1ELPAT** [comment]
![tmc2208 uart mode](https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/assets/99099374/17602b7f-4a49-49ef-94a1-932a84fe5770)
Me funciono solde los 2 pats juntos y cuando conecte la placa funcionaba igual lo cheque en el pronterface con el comando m122 y funciono muchas gracias a todos
