### ISSUE TITLE
Thermistor Short

### ISSUE THREAD

**Issue by Tomthi** [bigtreetech/BIGTREETECH-SKR-V1.3#171]
Has anyone had a issue where the thermistor circuit burned out? According to support there was a "thermistor leakage" Which I'm still not entirely sure what that means.  Does that mean the thermistor is shorted and is sending high current into the thermistor circuit? I ordered a new board but I want to avoid this and I'm not sure where to start troubleshooting. 

The bard was running great for 4 months.

**Comment by Tomthi** [comment]
I found the root cause.

**Comment by JeffMedd** [comment]
Hi, I think I have something similar, what was the root cause in your case?
