### ISSUE TITLE
SKR 1.4,  CR10S Bed Temperature Error

### ISSUE THREAD

**Issue by Ru83nG** [bigtreetech/BIGTREETECH-SKR-V1.3#189]
I get a "Printer Halted Error"  every time the bed temperature reaches 72°!!
Transitioned from the Creality board v2.1, where everything worked fine.  Now with this board I cannot figure it out.  I tried it with an external bed mosfet and with the on-board as well.  Same issue.
I checked the connection/polarity of the pins and all is as it was with the Creality 2.1.  
I am stumped that only at 72°, the bed temp will not go above that.
Checked the cabling to bed, then switched back to creality 2.1 board and all works fine!!
Using Marlin 2.0.1
Could anyone help?
Thanks in advance

**Comment by Arganaz** [comment]
check your marlin code, you might have set a temperature limit or double check thermistor and bed connections for proper placement.
my bet is on the code.... switching between chamber and bed settings, maybe?
good luck

**Comment by Ru83nG** [comment]
Thanks. done that also.  I think I remember marlin by heart now.I switched back to creality board 2.1 which works fine. I,ve put too many research hours into these boards.  Sent them, 1.3 and 1.4, back for refund.  With just a few days left in "return window." 
 I think I am ready to invest in something more solid and documented.

**Comment by lijinlin19970813** [comment]
> Thanks. done that also. I think I remember marlin by heart now.I switched back to creality board 2.1 which works fine. I,ve put too many research hours into these boards. Sent them, 1.3 and 1.4, back for refund. With just a few days left in "return window."
> I think I am ready to invest in something more solid and documented.

Can you send me your configuration.h / configuration_adv.h file to see?I can help you check.
