### ISSUE TITLE
TMC2209 and SKR 1.4 Turbo

### ISSUE THREAD

**Issue by delwinbest** [bigtreetech/BIGTREETECH-SKR-V1.3#192]
Hi Team,
I've spent a few hours trying to get the TMC2209 to register on the SKR 1.4 TURBO. I've tried 5 different drivers, and have followed your instructions. I've also tried your supplied firmware, and I have my own. Each time I get 'bad response'. 

Please help! I currently use these drivers in a MKS board without any trouble. 
My current config can be found here: https://github.com/delwinbest/Marlin_BIBO2_touch_dual/tree/btt_skr_v1.4_turbo

Attached is a photo of my jumper connection. I can't find anything else I can try. Could you perhaps provide a schematic for the Turbo board? 

Photo of Jumpers: https://github.com/delwinbest/Marlin_BIBO2_touch_dual/blob/btt_skr_v1.4_turbo/jumpers.png

**Comment by delwinbest** [comment]
Ignore. Found the problem: The board must be powered by main supply to test TMC drivers. Not USB. 5 hours lost :D

**Comment by wallen83** [comment]
so you can't check status in pronterface with only usb power? I spent 4 hours with it yesterday ...
also has problems with tmc2209 and sensorless homing .. it does not want to stop. can't find what's wrong. are you running sensorless homing?       (skr v1.4 board)

**Comment by Fuglys** [comment]
waw thanks that can be the problem why M112 gave a kill

**Comment by delwinbest** [comment]
@wallen83 that was my experience. I could not get it to work until I powered up the board with my 12/24V Supply. Also lost hours trying. 
I'm using sensor-less homing which works well.

**Comment by thetechy2** [comment]
> also has problems with tmc2209 and sensorless homing .. it does not want to stop. can't find what's wrong. are you running sensorless homing? (skr v1.4 board)
1.4 turbo 2209 trouble with sensorless homing here please reply if youve found anything

**Comment by wallen83** [comment]
![F4001081-E6D8-417A-AF7C-1C48D087B5B9](https://user-images.githubusercontent.com/60329442/73785112-fa67e200-4796-11ea-97f1-c41e56de0318.jpeg)


yes i use sensor less on my skr1.4/TMC2009 UART.   I had removed // on the wrong sensor less homing in marling fw.  I had removed it on sensor_less_probing  🙈

you have all the pins left? (on TMC2009)

**Comment by thetechy2** [comment]
> you have all the pins left? (on TMC2009)

yeah all the pins are there. when i try to home it, it just fails and halts the printer

**Comment by drphil3d** [comment]
HEY GUYS! MAKE SURE TO CUT the pin on the Z stepper driver if your using tmc2209 RTFM!

**Comment by drphil3d** [comment]
Also, I learned this one the hard way, if you enable sensorless homing on Z axis, the pins file changes the input from Z-STOP to PWR-DET port.
