### ISSUE TITLE
Missing schematics

### ISSUE THREAD

**Issue by VanessaE** [bigtreetech/BIGTREETECH-SKR-V1.3#2]
The schematic and board trace layout files are missing....

**Comment by jourjine** [comment]
Same request for schematic

**Comment by sciencecentredelft** [comment]
Check this website: http://elsainmac.tistory.com/m/470
Translate it to English

**Comment by VanessaE** [comment]
I see no schematics on that site.

**Comment by zillarob** [comment]
This is what we are looking for, but for v1.3

![scm](https://user-images.githubusercontent.com/42916376/55080056-cfd7d380-5073-11e9-8909-5426b3cd5bfc.JPG)

**Comment by bigtreetech** [comment]
https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/hardware/SKR-V1.3-SCH.pdf here is the SKR V1.3 schematic

**Comment by VanessaE** [comment]
Yay!

**Comment by bill-orange** [comment]
Schematic link no longer works.

**Comment by VanessaE** [comment]
the moved the repo a bit, new link is https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/BTT%20SKR%20V1.3/hardware/SKR-V1.3-SCH.pdf

**Comment by VanessaE** [comment]
@bigtreetech  the schematics are still missing for the v1.4 though.

**Comment by Coffee0297** [comment]
@bigtreetech can you please upload schematics for the 1.4? as soon as possible

**Comment by GeorgesOatesLarsen** [comment]
This should be closed

V1.4 schematics are available here:

https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/BTT%20SKR%20V1.4/Hardware/BTT%20SKR%20V1.4-SCH.pdf
