### ISSUE TITLE
SKR 1.4 Turbo USB Detection

### ISSUE THREAD

**Issue by Baconadors** [bigtreetech/BIGTREETECH-SKR-V1.3#206]
Hi all, 

Just getting my SKR 1.4 Turbo wire up and I seem to be having a problem connecting it via USB.
I have changed the jumper over to USB power. I plug in the provided USB cable to the board and then to my computer.

However it will not show up in explorer.

I check the device manager and I can see a "USB Serial Device (COM4) flashing every few seconds.
I know that this is the SKR board as this behavior stops when I unplug it.

What is the issue? See the attached GIF.
![2020-01-25_10-48-45](https://user-images.githubusercontent.com/27475467/73124377-4da09000-3f60-11ea-9db1-080db957edc8.gif)

**Comment by bartofborg** [comment]
You need the driver for it, https://github.com/HobbyComponents/CH340-Drivers

**Comment by Baconadors** [comment]
Unfortunately, that driver won't install.

https://i.imgur.com/xpB9M7L.gif

**Comment by bartofborg** [comment]
if you open the instruction pdf, ther is a link in it to a driver from bigtree there. it is a dropbox address, you'll have to type it in manually but, it worked for me

**Comment by Baconadors** [comment]
I disabled signed driver checking and it allowed me to install both the CH340 driver and the lpc176x_usb_driver included in github.

Still have the same issue with it showing. Same behavior as in the original gif.

**Comment by Baconadors** [comment]
If I uninstall the driver right before it disappears, when the device reappears it will show "Marlin USB Device"
It this disappears and the cycle in the original gif continues. At this point I have indeed installed the drivers.

![mmc_2020-01-25_13-05-46](https://user-images.githubusercontent.com/27475467/73126045-71b99c80-3f73-11ea-8d88-8530b1bcd635.gif)

**Comment by Baconadors** [comment]
When I right click the device and choose update, I was able to switch it over to Marlin USB Serial driver.
![mmc_2020-01-25_13-17-30](https://user-images.githubusercontent.com/27475467/73126175-23a59880-3f75-11ea-98e3-af06fa1d1c75.gif)

However, original behavior continues.

**Comment by bartofborg** [comment]
Good! You ready to go then.Jeff ZackodnikOn Jan. 25, 2020 12:18 p.m., Baconadors <notifications@github.com> wrote:When I right click the device and choose update, I was able to switch it over to Marlin USB Serial driver.

However, original behavior continues.

**Comment by Baconadors** [comment]
No, I'm not ready to go.

It still doesn't work.

**Comment by Baconadors** [comment]
![2020-01-25_13-38-24](https://user-images.githubusercontent.com/27475467/73126430-fefef000-3f77-11ea-827d-9da94971a647.gif)

**Comment by bartofborg** [comment]
Have you connected the USB to your computer and opened pronterface or whatever terminal program your using and tried connecting to the board on the com port the marlin device is?




Get Outlook for Android







On Sat, Jan 25, 2020 at 12:35 PM -0700, "Baconadors" <notifications@github.com> wrote:












No, I'm not ready to go.


It still doesn't work.



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.







No, I'm not ready to go.

It still doesn't work.

**Comment by Baconadors** [comment]
Wiring issue.

Couldn't directly see what was causing a problem, but I redid all of the wiring and made sure to put electrical tape on anything that could short the board.

**Comment by PapiOrso** [comment]
I solved the problem by reloading the original firmware provided in the micro SD. I used a usb card reader to rename the original file from .CUR to .BIN then I inserted the SD in the board.

**Comment by saintofinternet** [comment]
> I solved the problem by reloading the original firmware provided in the micro SD. I used a usb card reader to rename the original file from .CUR to .BIN then I inserted the SD in the board.

Does that orginal firmware work for CoreXY?

**Comment by lakeland3516** [comment]
the reason the inf file wont' work for people using windows 10 or other windows i found that the 64 bit machines won't recognize the file but if you have a old 32 bit computer kicking around it'll load properly and recognize it so basically saying some one needs to write one for a 64 bit system
