### ISSUE TITLE
Lerdge TMC2209 UART not working

### ISSUE THREAD

**Issue by Narolakk** [bigtreetech/BIGTREETECH-SKR-V1.3#209]
I don't get the UART mode to work.  I tried different things.  
I jumpered the TX / RX pins with a jumper and I soldered down two pins that go into the socket.  always get connection error with M122.

I have not yet tried the red pins for bridges.

SKR 1.4 Turbo, Marlin 2.1Dev

![375D5154-54B4-4203-BB60-E601B020111E](https://user-images.githubusercontent.com/48066111/73235636-88d4d600-418f-11ea-97db-92ab3e117e47.jpeg)
![9B0AA686-FF1F-4972-AC8F-A903FA0E6A2F](https://user-images.githubusercontent.com/48066111/73235637-88d4d600-418f-11ea-925a-0ae67b7fca0c.jpeg)
![AE562533-85BD-4FC6-AFBB-26CFACBF27FF](https://user-images.githubusercontent.com/48066111/73235688-c20d4600-418f-11ea-8591-181e6e08a8bf.jpeg)
![7244D180-A78A-4192-B249-D60820473364](https://user-images.githubusercontent.com/48066111/73235689-c20d4600-418f-11ea-852c-d0de39402e99.jpeg)
![463AA11E-5FFA-419A-B88B-A2757AC7AE2E](https://user-images.githubusercontent.com/48066111/73235767-11ec0d00-4190-11ea-8fee-a1a329daa7b2.jpeg)

**Comment by Narolakk** [comment]
UART works!  you have to solder two pads together on the bottom.
![Uploading 802C5F18-EAD1-45A7-AD7E-D2BDBBAA95D8.jpeg…]()

**Comment by PaedeG** [comment]
I've got exactly the same problem here..
I soldered as you mentioned..  
have you done only the soldering to get it work? or are you using the jumper (rx/tx) too?
Thanks a lot

![2020-03-05 16_43_24-0% -](https://user-images.githubusercontent.com/60323080/75998096-9274fa80-5f00-11ea-92f8-515cf053cb34.png)

**Comment by phiphe** [comment]
I have to put this 2209 v1.0 in skr.1.3... can you help.me?.
I must to insert in down side 2 pins and sold this?.
Thanks and regards.

**Comment by mgpsantos** [comment]
Hi
Did you solve the lerdge tmc2209 driver problem in uart mode?

**Comment by derTimm0** [comment]
i know, old tread ;-) but i has the same problem. can some one help me? ;-)
