### ISSUE TITLE
skr 1.4 turbo jumpers configured for uart with tmc2209 made a puff of smoke

### ISSUE THREAD

**Issue by thetechy2** [bigtreetech/BIGTREETECH-SKR-V1.3#216]
so i had the jumpers configured for spi and i couldnt get sensorless homing to work. i thought i would switch to uart mode as described in the instructiont and see if that works. as soon as i applied power a puff of smoke came out. i have no idea what to do now

**Comment by thetechy2** [comment]
pretty sure it fried a driver

**Comment by stantond** [comment]
2209s don't support SPI

**Comment by lliuw** [comment]
hey @thetechy2 ,
did you find why the driver fried? or you found something else?
