### ISSUE TITLE
EEPROM version mismatch (EEPROM=ERR Marlin=....

### ISSUE THREAD

**Issue by GeminiServer** [bigtreetech/BIGTREETECH-SKR-V1.3#218]
Any ideas why the EEPROM does not work with the latest Marlin bugfix2.0.x?

SENDING:M502
echo:Hardcoded Default Settings Loaded
>>> m500
SENDING:M500
Error:Field recovery_enabled mismatch.
Error:Field recovery_enabled mismatch.

>>> m501
SENDING:M501
echo:EEPROM version mismatch (EEPROM=ERR Marlin=V76)
echo:Hardcoded Default Settings Loaded
Error:Field recovery_enabled mismatch.
Error:Field recovery_enabled mismatch.

--> BTT SKR 1.4 Pro 
My Marlin config and src --> https://github.com/GeminiServer/GeminiServer-Marlin/tree/4MAX-2.0.x-SKR-1.4-Pro

**Comment by GeminiServer** [comment]
Fixed on my repo.

**Comment by bleedingpixels** [comment]
link doesn't work to fix
