### ISSUE TITLE
Missing schematics for SKR 1.4

### ISSUE THREAD

**Issue by tvixen** [bigtreetech/BIGTREETECH-SKR-V1.3#243]
Could you please upload the schematics for the SKR 1.4 board.

Thanks in advance

**Comment by thisismike97** [comment]
Do you mean this one?

https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/BTT%20SKR%20V1.4/Hardware/BTT%20SKR%20V1.4PIN.pdf

**Comment by paulgking** [comment]
That isn't a schematic, I think he means (and I would certainly like) a 1.4 version of this for 1.3 https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/BTT%20SKR%20V1.3/hardware/SKR-V1.3-SCH.pdf

**Comment by tvixen** [comment]
We already have the schematics for skr 1.3.  I would like to have it for skr 1.4.

**Comment by SusiBiker** [comment]
As paulgking described above, SKR 1.4 schematics would be really useful.

**Comment by AnubisCZ** [comment]
Please SKR 1.4 scheme.

**Comment by jstaylor11** [comment]
I would love to have a look at this as well so I can troubleshoot some issues I am having with the SKR 1.4 Turbo board and the extruder (TMC2208 3.0) not working.

**Comment by majo91** [comment]
I need it as well! @bigtreetech please upload the schematic. thanks!

**Comment by asdmin** [comment]
172 open issues at writing this entry and the fact that they crammed 1.4 documentation into the 1.3 project clearly shows that BTT only uses github as a content delivery system.

In other words, you are shouting into a black hole here guys. Buy the 1.3 instead. Or any other vendor who can properly document their product.

**Comment by asdmin** [comment]
dup to https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/issues/184

**Comment by DeviousPenguin** [comment]
> I would love to have a look at this as well so I can troubleshoot some issues I am having with the SKR 1.4 Turbo board and the extruder (TMC2208 3.0) not working.

Are you running Klipper firmware?

**Comment by thisismike97** [comment]
@tvixen As of 7 hours ago, the schematics have been uploaded, please close this issue and goodluck with your project.

**Comment by tvixen** [comment]
Thanks for upload. 

Case closed.
