### ISSUE TITLE
TMC Connection Error

### ISSUE THREAD

**Issue by stricktech** [bigtreetech/BIGTREETECH-SKR-V1.3#25]
lcd shows TMC CONNECTION ERROR , and if i send m122 i get all low on xyz and e.

i have soldered the j2 pads, set TMC2208 , set both serial ports as shown in the instructions in config, set tmcdebug in config adv. 
I have all jumpers removed except the uart jumpers.

is there something im missing?

**Comment by SISLANGER** [comment]
Just checking you set the firmware as in the video

https://www.youtube.com/watch?v=oaXfXkPYHpw

**Comment by Javi91ac** [comment]
Try to solder 3 pads j2. So I fix it

**Comment by Yannick06300Pat** [comment]
Alors oui souder sur j2 2/3 ou 1/2/3
Réussi avec tmc2208 v3
![AA9450D5-352E-42EB-9FAA-BE66FAEE14A0](https://user-images.githubusercontent.com/50111931/58507880-083e7f80-8193-11e9-8e4d-7d80429e5bfa.jpeg)

**Comment by SISLANGER** [comment]
V3 Doesn't need soldering if you got the ready soldered version

if need to solder
https://www.makenvape.uk/3d-printing/3d-printing-guides/skr-v1-3-setup-guide/#TMC2208_SOLDER

**Comment by stricktech** [comment]
Sorry, should hahavhahaveclosed this long ago, its bc I was powered with usb at the time.
