### ISSUE TITLE
Lags when printing via USB

### ISSUE THREAD

**Issue by angry-elf** [bigtreetech/BIGTREETECH-SKR-V1.3#275]
I have SKR 1.4 Turbo board.
I'm trying to print via USB port, connecting to Octoprint or desktop's Pronterface.

Looks like there are lags in connection. When I prints curved lines (like cylinders), there are small pauses causing oozes on this curves. Printing same gcode from SD (via TFT24) is ok, without pauses and oozes. 

Is it designed so? Can I use USB port on this board for printing? Is there specific options for marlin to resolve this issue?

**Comment by kkosa1** [comment]
Had similar problems with SKR PRO V1.1 that were solved by updating Marlin to current bugfix.  It was a communications issue

________________________________

**Comment by angry-elf** [comment]
I tried to disconnect TFT24 leaving only Octoprint (via USB) connected and seems all fine now. Looks like this board (or Marlin) can't handle multiple hosts connected.

**Comment by angry-elf** [comment]
Problem solved with new marlin build (2.0.5.2). Now TFT24 and Octoprint are connected, printing from Octoprint via USB is fine.
