### ISSUE TITLE
Skr 1.4 turbo TMC 2209 dual z motors and dual z endstops. What to change in Marlin?

### ISSUE THREAD

**Issue by Ndawen** [bigtreetech/BIGTREETECH-SKR-V1.3#282]
I have a corexy printer that uses 2 z motors and 2 z endstops . I plugged one z motor into z port and the other into e1 port. One of the z endstop switches into z min ,not sure on the other but atm it's plugged into e1det. What do I need to change in Marlin to get this to work,and do I need to change anything in the pins.h file?

Thanks 
David

**Comment by Sundancer78** [comment]
hi, I think the second Z-motor does not belong to the E1M connection, rather to the "ZMB" connection directly next to the "ZMA" connection. At E1M comes the second extruder motor or nothing if only one nozzle.
In Marlin - configuration.h you can define the second driver Z2 under "stepper drivers", possibly also E1 if available.
in configuration_adv.h you simply search for Z2 and change the settings as you need them.
![vsc](https://user-images.githubusercontent.com/42901216/78086029-fc2bdb80-73bc-11ea-943b-59a6bdcd8bbc.png)
