### ISSUE TITLE
Thermistors read 300+ degrees at all times

### ISSUE THREAD

**Issue by girrrrrrr2** [bigtreetech/BIGTREETECH-SKR-V1.3#287]
Im hooking up a 100K thermistor, and i get 300+ degrees at all times, no matter what thermistor I set it up for... some go higher to 600 degrees, but the proper setup for the ones that im putting in read 360 degrees.

im starting to think its the board at this point, just because the thermistor reads perfect on an ohmmeter, and perfect on another printer

**Comment by jayala1213** [comment]
I have the same issue. I'm not sure how to fix it.

**Comment by girrrrrrr2** [comment]
> I have the same issue. I'm not sure how to fix it.

My board was messed up and i had to get another.
