### ISSUE TITLE
How to map physical pins on skr v1.3 to ADC ?

### ISSUE THREAD

**Issue by bdelia** [bigtreetech/BIGTREETECH-SKR-V1.3#298]
Hey,
I am newbie to wiring up a board for a 3d printer.  I am having trouble determining which physical pins on the board represent possible analog pins.  For instance how do I know which physical pin represents P0_02_A7?  I have been studying the SKR V1.3-PIN diagram, but I have not been able to figure this out.  Any insights would be greatly appreciated.
Thanks in advance.

**Comment by bdelia** [comment]
I have figured this out...

**Comment by hdano1** [comment]
So how about to write it???
I need to know which pin is for ADC for lcd2004 display to work 5 buttons.
