### ISSUE TITLE
No USB connection on Marlin but I do with Smoothie

### ISSUE THREAD

**Issue by ped7284** [bigtreetech/BIGTREETECH-SKR-V1.3#319]
This is a self created issue.  This is a DIY printer with TFT35, SKR 1.3 TMC2208
I keep adding things to the SKR 1.3 till it breaks.  different extruder, moving limits sensors.  I think I tightened the hotend and since it is a volcano the heat element gets very close to the cool part.  That is the last thing I did that could cause an electrical short. All other connections are tight and the printer has been working great!  I am using VS studio platformIO Marlin bugfix 2.0

History: I noticed the hotend was on after power up. touched it and burnt my finger.   I reset and the the same issue.  cycle power and same thing. I hooked up to the PC and USB drive showed gibberish characters and it looked like corrupted files.  So then I formatted SDcard while it was in the SKR and that was the last of it. after that the USB would not show up on the PC.  I took out the SD card, placed in PC and it worked so I formatted the SD card again and installed the firmware.bin. put back in the SKR and no communications to TFT and hotend still on.  I took out the SD card and it showed firmware.cur so it took but still no USB drive and no TFT connection.

Tried other SD card, different power supply, int vs external pin, disconnected everything and still nothing.   I ended up buying a new board.

BUT then I installed a firmware.BIN from a smoothie location and now the SKR shows the USB connection on the PC and it works with various Mcode commands. https://github.com/bigtreetech/Smoothieware/tree/edge/FirmwareBin

So for a $20 board I have already spent the money typing but I thought this was weird and wanted to see if others have some ideas....  Thanks,  Phill

**Comment by antonrr90** [comment]
Funny thing about both BTT & MKS MainBoards, neither brand can manage to get there TFT Ports to work, something that's unusual since TFT has more or less been a standard for over 3 years.
