### ISSUE TITLE
SKR v1.3 unable to get part cooling fan to work

### ISSUE THREAD

**Issue by thezak48** [bigtreetech/BIGTREETECH-SKR-V1.3#326]
As it says in the title, I have tried everything, FAN_FAN1, P2_04, and the second fan pin and nothing, I know the fan works as I when I put it on the 24v from the PSU it works perfectly. I have added my configs

[Marlin.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/files/4640255/Marlin.zip)

**Comment by acinsa** [comment]
check the fuse F2

**Comment by thezak48** [comment]
Somehow fixed the issue, no idea how but I'll take it xD
