### ISSUE TITLE
SKR1.4 Filament Sensor not responding / stop during Print

### ISSUE THREAD

**Issue by elmolinger** [bigtreetech/BIGTREETECH-SKR-V1.3#354]
Hi Guys,

I try to get my Runout Sensor running on the SKR1.4. Unfortunately so far without success.

I went through almost all configurations. The sensor works and IO voltage was measured at the sensor out.

my FRS config
`#define FILAMENT_RUNOUT_SENSOR`
`#if ENABLED(FILAMENT_RUNOUT_SENSOR)`
 ` #define NUM_RUNOUT_SENSORS   1     // Number of sensors, up to one per extruder. Define a FIL_RUNOUT#_PIN for each.`
  `#define FIL_RUNOUT_INVERTING false // Set to true to invert the logic of the sensor.`
`  #define FIL_RUNOUT_PULLUP          // Use internal pullup for filament runout pins.`
 ` //#define FIL_RUNOUT_PULLDOWN      // Use internal pulldown for filament runout pins.`
`  #define FILAMENT_RUNOUT_SCRIPT "M600"`
`  #define FILAMENT_RUNOUT_DISTANCE_MM 7`
`  #ifdef FILAMENT_RUNOUT_DISTANCE_MM`
`    //#define FILAMENT_MOTION_SENSOR`

Unfortunately I didn't get any signal via M119 at runout pin P1_26.
Only when I set FIL_RUNOUT_PIN to P1_25 did M119 display triggered / open during the test.
`#define FIL_RUNOUT_PIN                     P1_25  // E0DET`
`#define FIL_RUNOUT2_PIN                    P1_26  // E1DET`
>Reporting endstop status
x_min: open
y_min: open
z_min: TRIGGERED
z_probe: TRIGGERED
filament: TRIGGERED
 m119
SENDING:M119
Reporting endstop status
x_min: open
y_min: open
z_min: TRIGGERED
z_probe: TRIGGERED
filament: open
SENDING:M412
echo:Filament runout ON
Filament runout distance (mm): 7.00

Does anyone have experience here how to set the sensor correctly?

Best regards

**Comment by spiffy781** [comment]
Same issue,  SKR 1.4 machine will start print then after 10/15 mm of extrusion will go into filament change mode.
