### ISSUE TITLE
TFT35 V3 and touch mode

### ISSUE THREAD

**Issue by killrob** [bigtreetech/BIGTREETECH-SKR-V1.3#367]
hi all,
is possible that in Marlin mode i can change jerk settings and i can't in touch mode?
and changes made in Marlin mode affects also the touch mode?
there is any method to do it in touch mode?
Thank you all

**Comment by zonalimitatore** [comment]
No,in touch mode there isn't jerk's menu (for now,maybe next)
Yes,changes made in Marlin mode or touch are the same.Both refer to eeprom memory (M500)

**Comment by killrob** [comment]
@zonalimitatore sei italiano? con quel nick :D anyway thanks a lot

**Comment by zonalimitatore** [comment]
Si :D :D :D
