### ISSUE TITLE
SKR 1.4 turbo (w/ mks tmc2209 v2) endstops not working

### ISSUE THREAD

**Issue by RunLoganRun** [bigtreetech/BIGTREETECH-SKR-V1.3#375]
I'm pulling my hair out at this point; x/y/z endstops/probe trigger fine, but aren't stopping the motors. 

I've tried so many different marlin configs; including swaping around pins. I've tried different jumper/bending of pin combinations/reversing wires/etc. All the wiring seems fine.

Does anyone have know on how I might fix this?

Edit: OK so I've resolved the issue now. For any future people with similar issues: 
1. comment out #define ENDSTOPPULLDOWNS & UPS
2. uncomment pulldowns individually on x/y & pullups z/zprobe (if you're using a probe; if mechanical switch use PULLDOWNS)

**Comment by nicobits46** [comment]
hi did u solve that prblem? i´m going thru the same here i´m going crazy ,,,,,,, any help would be very gratefull
