### ISSUE TITLE
Bootloader for LPC1768

### ISSUE THREAD

**Issue by Pilson66** [bigtreetech/BIGTREETECH-SKR-V1.3#39]
Where can I get and how to install the initial bootloader for the newly soldered LPC1768 ?

**Comment by oneofnine** [comment]
Seems BigTreeTech no longer answer messages.

Apparently it's the smoothieware bootloader that's used.

[http://smoothieware.org/flashing-the-bootloader](url)

**Comment by Pixel-Soup** [comment]
I tried the smoothieware one and it didn't work.

**Comment by Pilson66** [comment]
@Pixel-Soup I useв this bootloader at lest 4 times, and it worked.
