### ISSUE TITLE
BuildingSKR-1.4 Turbo Firmware, completely stock, HAL error

### ISSUE THREAD

**Issue by Vnldwth** [bigtreetech/BIGTREETECH-SKR-V1.3#393]
Afternoon all, I'm trying to build and use the skr 1.4 turbo, replacing my fried 1.3 with it.  
I configured everything, including the UART settings for the 2208's, and I'm getting a rather weird error?  I've tried a few different things, but can't get to to finish.  any ideas?  log below.

`> Executing task in folder Marlin-2.0.x-SKR-V1.4-Turbo: C:\Users\evanl\.platformio\penv\Scripts\platformio.exe run <

Processing LPC1769 (platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.2.zip; board: nxp_lpc1769; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/nxplpc-arduino-lpc176x/nxp_lpc1769.html
PLATFORM: NXP Arduino LPC176x 0.1.1 > NXP LPC1769
HARDWARE: LPC1769 120MHz, 31.97KB RAM, 464KB Flash
DEBUG: Current (cmsis-dap) On-board (cmsis-dap) External (blackmagic, jlink)
PACKAGES:
 - framework-arduino-lpc176x 0.2.4
 - toolchain-gccarmnoneeabi 1.90201.191206 (9.2.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ off, Compatibility ~ strict
Found 6 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Servo> 1.0.0
|-- <LiquidCrystal> 1.0.0
|-- <U8glib-HAL> 0.4.1
|-- <TMCStepper> 0.7.1
|-- <Adafruit NeoPixel> 1.3.0
|-- <SailfishLCD>
Building in release mode
upload disk:  G:
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\DebugMonitor.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\HAL.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\HAL_SPI.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\MarlinSerial.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\fast_pwm.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\include\digipot_mcp4451_I2C_routines.c.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\main.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\persistent_store_flash.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\persistent_store_sdcard.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\timers.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\u8g\LCD_I2C_routines.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\u8g\LCD_pin_routines.c.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\u8g\u8g_com_HAL_LPC1768_hw_spi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\u8g\u8g_com_HAL_LPC1768_ssd_hw_i2c.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\u8g\u8g_com_HAL_LPC1768_st7920_hw_spi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\u8g\u8g_com_HAL_LPC1768_st7920_sw_spi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\u8g\u8g_com_HAL_LPC1768_sw_spi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\usb_serial.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\HAL_LPC1768\watchdog.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\HAL_spi_L6470.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\backtrace.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwarm.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwarm_arm.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwarm_thumb.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwarmbytab.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwarmmem.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwinder.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwmemaccess.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\eeprom_i2c.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\eeprom_spi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\persistent_store_api.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\servo.cpp.o
Compiling .pio\build\LPC1769\src\src\Marlin.cpp.o
Compiling .pio\build\LPC1769\src\src\core\multi_language.cpp.o
Compiling .pio\build\LPC1769\src\src\core\serial.cpp.o
Compiling .pio\build\LPC1769\src\src\core\utility.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\I2CPositionEncoder.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\Max7219_Debug_LEDs.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\babystep.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\backlash.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\baricuda.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\abl\abl.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\bedlevel.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\mbl\mesh_bed_leveling.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\ubl\ubl.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\ubl\ubl_G29.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\ubl\ubl_motion.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\binary_protocol.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bltouch.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\cancel_object.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\caselight.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\closedloop.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\controllerfan.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\dac\dac_dac084s085.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\dac\dac_mcp4728.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\dac\stepper_dac.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\digipot\digipot_mcp4018.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\digipot\digipot_mcp4451.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\emergency_parser.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\fanmux.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\filwidth.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\fwretract.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\host_actions.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\joystick.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\leds\blinkm.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\leds\leds.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\leds\neopixel.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\leds\pca9632.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\leds\printer_event_leds.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\leds\tempstat.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\mixing.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\pause.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\power.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\power_loss_recovery.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\prusa_MMU2\mmu2.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\runout.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\snmm.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\solenoid.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\spindle_laser.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\tmc_util.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\touch\xpt2046.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\twibus.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\G26.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\G42.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\M420.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\abl\G29.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\abl\M421.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\mbl\G29.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\mbl\M421.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\ubl\G29.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\ubl\M421.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\G28.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\G33.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\G34_M422.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\G425.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\M100.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\M12.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\M425.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\M48.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\M665.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\M666.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\M852.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M200-M205.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M217.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M218.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M220.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M221.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M281.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M301.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M302.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M304.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M305.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M43.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M540.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M575.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M92.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M108_M112_M410.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M111.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M120_M121.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M17_M18_M84.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M211.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M226.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M280.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M3-M5.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M350_M351.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M380_M381.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M400.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M42.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M605.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M7-M9.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M80_M81.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M85.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M997.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M999.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\T.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\eeprom\M500-M504.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\L6470\M122.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\L6470\M906.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\L6470\M916-918.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\advance\M900.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\baricuda\M126-M129.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\camera\M240.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\cancel\M486.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\caselight\M355.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\clean\G12.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\digipot\M907-M910.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\filwidth\M404-M407.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\fwretract\G10_G11.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\fwretract\M207-M209.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\i2c\M260_M261.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\leds\M150.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\leds\M7219.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\macro\M810-M819.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\mixing\M163-M165.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\mixing\M166.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\pause\G27.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\pause\M125.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\pause\M600.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\pause\M603.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\pause\M701_M702.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\powerloss\M1000.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\powerloss\M413.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\prusa_MMU2\M403.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\runout\M412.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\trinamic\M122.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\trinamic\M569.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\trinamic\M906.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\trinamic\M911-M914.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\gcode.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\geometry\G17-G19.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\geometry\G53-G59.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\geometry\G92.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\geometry\M206_M428.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M110.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M113.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M114.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M115.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M118.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M119.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M16.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M876.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\lcd\M0_M1.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\lcd\M117.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\lcd\M145.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\lcd\M250.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\lcd\M300.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\lcd\M73.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\motion\G0_G1.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\motion\G2_G3.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\motion\G4.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\motion\G5.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\motion\G80.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\motion\M290.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\parser.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\probe\G30.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\probe\G31_G32.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\probe\G38.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\probe\M401_M402.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\probe\M851.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\probe\M951.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\queue.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\scara\M360-M364.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M20.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M21_M22.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M23.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M24_M25.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M26.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M27.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M28_M29.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M30.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M32.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M33.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M34.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M524.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sdcard\M928.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\stats\M31.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\stats\M75-M78.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temperature\M104_M109.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temperature\M105.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temperature\M106_M107.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temperature\M140_M190.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temperature\M141_M191.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temperature\M155.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temperature\M303.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\units\G20_G21.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\units\M149.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\units\M82_M83.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\HD44780\lcdprint_hd44780.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\HD44780\ultralcd_HD44780.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\dogm\lcdprint_u8g.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\dogm\status_screen_DOGM.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\dogm\status_screen_lite_ST7920.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\dogm\u8g_dev_ssd1306_sh1106_128x64_I2C.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\dogm\u8g_dev_st7565_64128n_HAL.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\dogm\u8g_dev_st7920_128x64_HAL.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\dogm\u8g_dev_tft_320x240_upscale_from_128x64.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\dogm\u8g_dev_uc1701_mini12864_HAL.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\dogm\u8g_fontutf8.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\dogm\ultralcd_DOGM.cpp.o
Marlin\src\lcd\dogm\status_screen_DOGM.cpp: In function 'void _draw_bed_status(bool)':
Marlin\src\lcd\dogm\status_screen_DOGM.cpp:238:16: warning: unused variable 'isHeat' [-Wunused-variable]
  238 |     const bool isHeat = BED_ALT();
      |                ^~~~~~
Compiling .pio\build\LPC1769\src\src\lcd\dogm\ultralcd_st7920_u8glib_rrd_AVR.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\extensible_ui\lib\dgus\DGUSDisplay.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\extensible_ui\lib\dgus\DGUSDisplayDefinition.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\flash_storage.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\media_file_reader.cpp.o
In file included from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\../../../../../inc/MarlinConfig.h:28,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\../../../ui_api.h:45,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\../compat.h:31,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\flash_storage.cpp:23:
Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\../../../../../inc/MarlinConfigPre.h:52:49: fatal error: ../HAL/HAL_LPC1768/inc/Conditionals_LCD.h: No such file or directory
   52 | #include HAL_PATH(../HAL, inc/Conditionals_LCD.h)
      |                                                 ^
compilation terminated.
Compiling .pio\build\LPC1769\src\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\basic\commands.cpp.o
*** [.pio\build\LPC1769\src\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\flash_storage.cpp.o] Error 1
In file included from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\../../../../../inc/MarlinConfig.h:28,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\../../../ui_api.h:45,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\../compat.h:31,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\media_file_reader.cpp:23:
Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\../../../../../inc/MarlinConfigPre.h:52:49: fatal error: ../HAL/HAL_LPC1768/inc/Conditionals_LCD.h: No such file or directory
   52 | #include HAL_PATH(../HAL, inc/Conditionals_LCD.h)
      |                                                 ^
compilation terminated.
In file included from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\basic\../../../../../../inc/MarlinConfig.h:28,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\basic\../../../../ui_api.h:45,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\basic\../../compat.h:31,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\basic\../../config.h:24,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\basic\../compat.h:20,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\basic\ftdi_basic.h:25,
                 from Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\basic\commands.cpp:23:
Marlin\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\basic\../../../../../../inc/MarlinConfigPre.h:52:49: fatal error: ../HAL/HAL_LPC1768/inc/Conditionals_LCD.h: No such file or directory
   52 | #include HAL_PATH(../HAL, inc/Conditionals_LCD.h)
      |                                                 ^
compilation terminated.
*** [.pio\build\LPC1769\src\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\archim2-flash\media_file_reader.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\lcd\extensible_ui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\basic\commands.cpp.o] Error 1
=============================================================================================================================================== [FAILED] Took 47.13 seconds =====================================================

Environment                   Status    Duration
----------------------------  --------  ------------
megaatmega2560                IGNORED
megaatmega1280                IGNORED
rambo                         IGNORED
FYSETC_F6_13                  IGNORED
sanguino_atmega644p           IGNORED
sanguino_atmega1284p          IGNORED
melzi                         IGNORED
melzi_optiboot                IGNORED
at90usb1286_cdc               IGNORED
at90usb1286_dfu               IGNORED
DUE                           IGNORED
DUE_USB                       IGNORED
DUE_debug                     IGNORED
LPC1768                       IGNORED
LPC1769                       FAILED    00:00:47.133
STM32F103RC                   IGNORED
STM32F103RC_fysetc            IGNORED
STM32F103RC_bigtree           IGNORED
STM32F103RC_bigtree_USB       IGNORED
STM32F103RC_bigtree_512K      IGNORED
STM32F103RC_bigtree_512K_USB  IGNORED
STM32F103RE                   IGNORED
STM32F103RE_bigtree           IGNORED
STM32F103RE_bigtree_USB       IGNORED
STM32F4                       IGNORED
STM32F7                       IGNORED
ARMED                         IGNORED
STM32F103VE_longer            IGNORED
mks_robin                     IGNORED
mks_robin_pro                 IGNORED
mks_robin_lite                IGNORED
mks_robin_lite3               IGNORED
mks_robin_mini                IGNORED
mks_robin_nano                IGNORED
jgaurora_a5s_a1               IGNORED
STM32F103CB_malyan            IGNORED
chitu_f103                    IGNORED
FLYF407ZG                     IGNORED
FYSETC_S6                     IGNORED
STM32F407VE_black             IGNORED
BIGTREE_SKR_PRO               IGNORED
BIGTREE_BTT002                IGNORED
teensy31                      IGNORED
teensy35                      IGNORED
esp32                         IGNORED
linux_native                  IGNORED
SAMD51_grandcentral_m4        IGNORED
rumba32_f446ve                IGNORED
mks_rumba32                   IGNORED
include_tree                  IGNORED
========================================================================================================================================== 1 failed, 0 succeeded in 00:00:47.133 ================================================`

**Comment by edwilliams16** [comment]
Why mess with a 7 month old version of Marlin.  Use a current one from the Marlin repository.

**Comment by Vnldwth** [comment]
> Why mess with a 7 month old version of Marlin. Use a current one from the Marlin repository.

Realized I had a few things wrong...  ended up wiping all my saved Marlin copies, either stock or distributed, and starting over.  an extra 30 minutes of sifting through config and machine settings and it worked.  Thanks for replying!
