### ISSUE TITLE
Unable to control fan speed

### ISSUE THREAD

**Issue by DuckieCZE** [bigtreetech/BIGTREETECH-SKR-V1.3#415]
Hello. I have a printer with BigTreeTech 1.4 Turbo board running latest marlin firmware.
I want to control a fan that cools the print. The fan is connected to FAN0 (pin 2.03).
It stays on all the time. I cannot control it through Gcode.
I also have an extruder fan that I configured to turn on at 50degrees C that works as it should. 
What can be the problem? Is it even possible to control the speed?
Any help will be appreciated :-)

I included configuration.h
                 configuration.adv.h
                 pins_BTT_SKR_common.h
[marlinconfig.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/files/5179591/marlinconfig.zip)

**Comment by Arakon** [comment]
Only one of the fan ports is PWM controllable, the other is simply always on at full speed.

**Comment by AnHardt** [comment]
> Is it even possible to control the speed?

No. It's a hardware limitation.

![image](https://user-images.githubusercontent.com/211931/92329981-ce357c00-f06b-11ea-8dff-de53313b3dd9.png)

**Comment by DuckieCZE** [comment]
> > Is it even possible to control the speed?
> 
> No. It's a hardware limitation.
> 
> ![image](https://user-images.githubusercontent.com/211931/92329981-ce357c00-f06b-11ea-8dff-de53313b3dd9.png)

Thank You for answering. I forgot to mention that the extruder fan is connected to HE1 (pin 2.4). So I should be able to control both of them, If the another one Is connected to FAN0 right? Both of these have PWM support.

**Comment by DuckieCZE** [comment]
So I finnaly solved the problem. I defined the FAN_PIN as Pin 2.04. The pin 2.03 was burned out

**Comment by DuckieCZE** [comment]
> Only one of the fan ports is PWM controllable, the other is simply always on at full speed.

Thank you for answering.
