### ISSUE TITLE
Stepper Extender on SKR v1.3

### ISSUE THREAD

**Issue by yoch2015** [bigtreetech/BIGTREETECH-SKR-V1.3#43]
I assigned an end stop pin because I wanted to set E to 3, but it does not work well.
Do you have any advice?
[pins_BIGTREE_SKR_V1.3.h]
#define E2_STEP_PIN        P1_27
#define E2_DIR_PIN         P1_29
#define E2_ENABLE_PIN      P1_04
#ifndef E2_CS_PIN
  #define E2_CS_PIN        -1
#endif

**Comment by carl1961** [comment]
haven't ventured that far yet, but maybe this video will help

https://www.youtube.com/watch?v=p6bAMM-XQL0

**Comment by yoch2015** [comment]
Thank you carl1961.
Because I use a diamond hot end, I needed three extruders.
Looking at the schematic of SKR v1.3, we decided that the end stop pin is not appropriate because it has passive components connected, and tried to assign another pin, it reports as it was successful.
The stepper motor moved with E2 active with the following settings and connections. As a bad effect, E0 will also be held during E2 operation.

**[pins_BIGTREE_SKR_V1.3.h]**
#define E0_STEP_PIN        P2_13
#define E0_DIR_PIN         P0_11
#define E0_ENABLE_PIN      P2_12
#ifndef E0_CS_PIN
//  #define E0_CS_PIN        P1_08
  #define E0_CS_PIN        -1
#endif

#define E1_STEP_PIN        P0_01
#define E1_DIR_PIN         P0_00
#define E1_ENABLE_PIN      P0_10
#ifndef E1_CS_PIN
//  #define E1_CS_PIN        P1_01
  #define E1_CS_PIN        -1
#endif

#define E2_STEP_PIN        P1_08
#define E2_DIR_PIN         P1_01
#define E2_ENABLE_PIN      P4_28
#ifndef E2_CS_PIN
  #define E2_CS_PIN        -1
#endif

![skr13board](https://user-images.githubusercontent.com/16486394/60431889-d8741300-9c3b-11e9-99eb-352f5905e1e1.png)
![DSC_0864 2](https://user-images.githubusercontent.com/16486394/60431971-08231b00-9c3c-11e9-9866-7ef8d0b75a45.JPG)
