### ISSUE TITLE
SKR 1.4 TURBO - Dual Z motors, second motor x2 steps

### ISSUE THREAD

**Issue by mwhite7** [bigtreetech/BIGTREETECH-SKR-V1.3#438]
When configured with 5x TMC 2209 drivers and the Z motors plugged into ZA and E1, the motor plugged into E1 seems to rotate twice as much as the other. Everything else works as expected; have tried every fix I could find posted to the internet but something tells me this situation is different and the bug lies within the E1 driven stepper rotating twice as much/fast. The problem persists when motors are swapped (E1 driven still x2 rotation). Motors work correctly when both are driven by the Z stepper (ports ZA & ZB), but I was really hoping to use the z auto-align feature (and now I'm stubborn that it should work the way I want it to since I've spent so much time on this).

Physically, everything is set up correctly according to every guide posted and the board pinout. Please let me know if pasting M122 results are of any help. 

config files here: [https://github.com/mwhite7/MW-Marlin]
Please also let me know if there are any other files needed to diagnose the issue.

Machine info:
Creality Ender 5 Plus
SKR 1.4 Turbo w/5x TMC2209
BTT TFT35 v3.0 display
Microswiss direct drive hotend

**Comment by mwhite7** [comment]
closed: issue was marlin bug that is now resolved

**Comment by injawoogie** [comment]
I have this same issue on Marlin 2.0.9.1. Did you know which version of Marlin this issue was resolved in?
