### ISSUE TITLE
SKR V1.3 TFT35 V2.0 Marlin not working

### ISSUE THREAD

**Issue by jasonfox7** [bigtreetech/BIGTREETECH-SKR-V1.3#449]
1. Smoothieware firmware from this github works. TFT35 V2.0 and SKR 1.3 connect and I can control the printer.

2. Marlin firmware from this github does not work. TFT35 V2.0 and SKR 1.3 fail to connect. Shows "no printer attached" and throws a "kill()" error after a few seconds. I cannot send commands to printer, and there is no communication at all. This is not a hardware issue, because the smoothieware firmware you have provided works correctly.

Something in the provided Marlin firmware is not set up correctly for the TFT35 V2.0 to communicate.

**Comment by Angeliqueratna** [comment]
may i have the firmware smoothiware for tft35 v2.0 and skr 1.3
