### ISSUE TITLE
SKR V1.4turbo doesnt connect thru USB after VSCode upload

### ISSUE THREAD

**Issue by Kscott73** [bigtreetech/BIGTREETECH-SKR-V1.3#456]
I moved the jumper to USB pins, then plugged USB cable into the computer. The board loaded up and connected to COM3.
I uploaded Marlin firmware thru VSCode

now it wont connect but powers up the board

**Comment by oldman4U** [comment]
Which serial scare defined in configuration?

**Comment by Kscott73** [comment]
i pulled the sd card and loaded file straight to the card. inserted card back in the skr board and plugged it in to the usb port. and guess what, it found the COM3 port.
#define SERIAL_PORT -1
#define SERIAL_PORT_2 0
#define BAUDRATE 250000


side: wont connect to pronterface
Serial error: could not open port 'COM3': WindowsError(5, 'Access is denied.')
SOLVED - VSCode was connected

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by Kscott73** [comment]
sry

**Comment by oldman4U** [comment]
No problem. Thank you and happy printing

Kscott73 <notifications@github.com> schrieb am Do. 5. Nov. 2020 um 18:05:
