### ISSUE TITLE
installed skr1.4 turbo in siderwinder x1

### ISSUE THREAD

**Issue by Kscott73** [bigtreetech/BIGTREETECH-SKR-V1.3#457]
hey 
i installed a BTT SKR 1.4 turbo into Sidewinder X1 today,  I found that the dual z and the extruder wires where crossed. And I had the extruder inverted so it was unloading when I selected load. but they were easy fixes. My problem is when I pressed "Home",  X,Y,Z went to the farthest positions.

**Comment by oldman4U** [comment]
Hi

You can change the homing direction in Marlin.

**Comment by Kscott73** [comment]
I need more. I am trying to run stallguard on x,y,z and it causes alot of errors

**Comment by oldman4U** [comment]
First problem solved?

Which error?

**Comment by Kscott73** [comment]
i started over, using marlin's bugfixed version.  i think problem was because i changed #define INVERT_X_DIR, i forgot to invert #define X_HOME_DIR

my coordinates are still inverted. extruder head moves in the right direction but home is 300,310,400
![btttft35](https://user-images.githubusercontent.com/73906818/98452027-7d98d880-2119-11eb-8220-f9bc7285b1b7.jpg)

**Comment by Kscott73** [comment]
i finally managed to get motors and coodinates correct
today i had help to get screen updated and correct(thank you oldman4)
so the only thing left is sensorless homing

![IMG_20201110_085610__01](https://user-images.githubusercontent.com/73906818/98686374-7a2e6880-2336-11eb-9836-6bc57d53928e.jpg)

**Comment by oldman4U** [comment]
Good.

But Marlin is not recognized and TFT firmware is completely outdated.

**Comment by Kscott73** [comment]
well;
marlin finally did get recognized
and finallly gave up on sensorless home, cut the pins and put the endstops back on
👎 :
but i have working machine. i will come back to sensorless home 6-12 months when it is more reliable.. just need 4 steppers
