### ISSUE TITLE
Slow booting on SKR V1.3

### ISSUE THREAD

**Issue by mrx23dot** [bigtreetech/BIGTREETECH-SKR-V1.3#481]
There is a 5-6second delay before Marlin's setup( ) is called, so I think it comes from the bootloader. It's also there without SD card inserted.

Is it possible to remove this delay? Why is it there?
Where can I find the source code for the bootloader? Why isn't in this repo?

**Comment by radek8** [comment]
https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/issues/346

**Comment by mrx23dot** [comment]
https://github.com/Marsman1970/SKR-V1.3-Bootloader 
only contains the original (ripped) bootloader binary, without source code.

@bigtreetech please upload the bootloader source or fix the issue.

**Comment by radek8** [comment]
Isn't that enough for you?

https://github.com/ardiehl/BTT_SKR_13_14_14T_SD-DFU-Bootloader

**Comment by mrx23dot** [comment]
sorry, I missed that

**Comment by mrx23dot** [comment]
continuing here https://github.com/ardiehl/BTT_SKR_13_14_14T_SD-DFU-Bootloader/issues/2
