### ISSUE TITLE
SD card not mounting in Octoprint

### ISSUE THREAD

**Issue by parsko41** [bigtreetech/BIGTREETECH-SKR-V1.3#484]
Hi,

My SD card is not mounting in Octoprint.  I'm trying to use the Firmware Updater add-on, and the support at that plug-in suggests I need to resolve getting my SD to mount onto Octoprint.

[Reference my issue with Firmware Updater here.](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/issues/175)

I have gone through the Firmware Updater procedure, but it won't show the card as mounted.

I do not see USB0 when I type the command `df -h` into a Putty terminal.  If my USB was mounted correctly, I should see it there.

Has anyone else come across this that could provide me with some advice?

SETUP:
Octoprint 0.15
SKR1.4 Turbo
Marlin 2.0 bugfix (days old)
(everything is the latest and greatest as this printer is only a few days old, new custom build)

Thanks,
-Parsko

**Comment by parsko41** [comment]
I still haven't figured this out.  Does anyone understand how the SD works?  While I am not able to do this, I would like to add an additional SD card reader (that I have) so I can store and run files from SD.  Is that necessary, or can that be done with the onboard micro SD card which holds the firmware?

I do not have any screen with a built in SD card.  I'm just trying to connect a breakout board to the same pins (also).

I am pointing out a 2nd issue here, in addition to my initial issue.  I'm primarily trying to solve the issue of updating the firmware.  I think me adding the 2nd SD may help me resolve the first.

[UPDATE]
I am very confused.  I have my SKR1.4 plugged into the USB port on my Pi.  I log into my Pi with Putty.  I enter `df -h`, and do not see usb0.  I `cd /media/usb0`, and I am able to `ls -al` and see my 'firmware.bin' file.  BUT, here is the catch, my SKR is not powered.  I have the jumper set to power from external, not USB.  How am I able to see the 'firmware.bin' file?  Is it possible I am seeing the Pi's 'firmware.bin' file and not the SKR's?

**Comment by parsko41** [comment]
Closing due to issue being resolved in link to the Firmware Updater in post 1.

**Comment by galamdring** [comment]
just came across this, and in case you didn't know, the folders you mount things into in linux exist as normal directories. If you copy something there when the mounted thing isn't mounted, it places the file in the directory on the parent device. When you mount the drive onto that mount point, it hides what otherwise exists in that directory, so you only see what is on the mounted device. When you unmount it, you can see the file that exists on the parent device again.
