### ISSUE TITLE
How can I use a stepper extender on the SKR 1.4 using TMC2208 in UART mode ?

### ISSUE THREAD

**Issue by rafik24** [bigtreetech/BIGTREETECH-SKR-V1.3#507]
Hi,
I am using an SKR 1.4 Turbo and I am adding 2 extra extruders stepper motors, for the first I am using a TMC2208 in UART mode on the E1 connector.
However for the third motor I am using a TMC2208 on an expender boar on exp1 pins for STEPS/DIR/EN.

I there a way to connect the PDN(UART) pin to the SKR 1.4 pins (Could maybe use the RX0 and TX0 pins of the TFT connector ? If yes what are these pins numbers / P1_XX ??)

Could you please help ?

Thanks in advance,
Rafik

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/110012032-5eedcb80-7d20-11eb-86e9-864cd87bf09f.png)


https://github.com/bigtreetech/BTT-Expansion-module/blob/master/BTT%20EXP-MOT/BTT%20EXP-MOT%20V1.0-SCH.pdf

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/110012316-b3914680-7d20-11eb-8ee7-5c19d71608d5.png)

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/110012707-197dce00-7d21-11eb-8692-82c706894274.png)

**Comment by rafik24** [comment]
Thank you so much @radek8 for your prompt response pointing me in the right direction.

I ordered an extension board so tomorrow will be the day of trialing.

Many thanks !!!

**Comment by rafik24** [comment]
Hi,

Received the expander board and configured the pins in klipper and all is working great.

Many thanks !
