### ISSUE TITLE
Skr 1.4 turbo firmware updating

### ISSUE THREAD

**Issue by Shayner2005** [bigtreetech/BIGTREETECH-SKR-V1.3#527]
SKR 1.4 turbo will change the .bin file to .cur file fine, but will not apply changes to actual board firmware. Tried both through SD card and with octoprint's firmware updater plugin.

**Comment by radek8** [comment]
Initialize eeprom

**Comment by Shayner2005** [comment]
> Initialize eeprom

Can you elaborate?

**Comment by Cheo7811** [comment]
@Shayner2005 you don't mention what printer and display you are using but if the option to Initialize EEPROM is not available on your display you can connect via USB to your car and use a serial program like Pronterface, once connected to your printer issue M502, M500 which will reset the EEPROM to the values in your firmware.

**Comment by Shayner2005** [comment]
> @Shayner2005 you don't mention what printer and display you are using but if the option to Initialize EEPROM is not available on your display you can connect via USB to your car and use a serial program like Pronterface, once connected to your printer issue M502 which will reset the EEPROM to the values in your firmware.

Ender 3 with a btt tft35 v3. Having screen issues prompted the firmware update. I use octoprint, however.

**Comment by Cheo7811** [comment]
Then you can send M502, M500 from Octoprint Terminal and see if that fix it.

**Comment by Shayner2005** [comment]
> 
> 
> Then you can send M502, M500 from Octoprint Terminal and see if that fix it.

Nope, no change.

**Comment by Dirge6** [comment]
This just now happened to me. Prusa TallBear w/ Phaetus Dragon, BTT 1.4Turbo, TMC2209s V1.2, and TFT43. Resetting EEPROM didn't work.  M504 shows OK.

**Comment by dirgesan** [comment]
An update: I believe my problem is solved. Seems to be updating. I rebuilt firmware with latest Marlin Bugfix. This also gave me a chance to finally install an AT24C with a 512 chip on the motherboard.

**Comment by radek8** [comment]
please close this ticket
