### ISSUE TITLE
Marlin firmware not showing board

### ISSUE THREAD

**Issue by jayala1213** [bigtreetech/BIGTREETECH-SKR-V1.3#530]
I'm using an Skr 1.4 turbo board with Marlin firmware but boards.h isn't showing my board an an option. The closest I see is a skr 1.3. Is the skr 1.4 turbo no longer compatible with marlin?

**Comment by radek8** [comment]
I see him there :-)
Attention:
SKR V1.3 has an LPC1768 processor.
SKR V1,4 has an LPC1768 processor.
SKRV1.4 Turbo has an LPC1769 processor.

**Comment by Cheo7811** [comment]
Yes, maybe it is better this way:
![image](https://user-images.githubusercontent.com/17888390/120630602-49935500-c467-11eb-803c-ac9aea0eeba3.png)

**Comment by jayala1213** [comment]
Hmmm that's really strange, mine doesn't show it. The closest it shows is skr 1.3. ![image](https://user-images.githubusercontent.com/74276786/120697058-7bf28180-c46a-11eb-915f-8f80fb2de43c.jpeg)

**Comment by Cheo7811** [comment]
That list looks very old, are you sure you have downloaded the latest Marlin 2.0.8.2 by pushing the CODE button and them the Download.ZIP?
![image](https://user-images.githubusercontent.com/17888390/120701799-9ac93600-c4b3-11eb-9182-e24faf4932f8.png)

**Comment by jayala1213** [comment]
> That list looks very old, are you sure you have downloaded the latest Marlin 2.0.8.2 by pushing the CODE button and them the Download.ZIP?
> 
> ![image](https://user-images.githubusercontent.com/17888390/120701799-9ac93600-c4b3-11eb-9182-e24faf4932f8.png)
> 
> 

Yeah I downloaded that version. Do you think that's the problem? I could've downloaded the wrong one.

**Comment by radek8** [comment]
@jayala1213 
You have version 2.0.0
She is very old

**Comment by radek8** [comment]
https://marlinfw.org/meta/download/

**Comment by jayala1213** [comment]
> https://marlinfw.org/meta/download/

Ok thank you so much! I'll try it!
