### ISSUE TITLE
extuder no responding

### ISSUE THREAD

**Issue by dimaknight1109** [bigtreetech/BIGTREETECH-SKR-V1.3#535]
I have a skr 1.3 board, 
I uploaded my firmware with the steps i followed from chris reliy's youtube video.
1) Everything else seems ok X home and moves well, same with Z
but when i move my bed, its moves smoothly but when i home y axis, it moves the bed a little and nothing, will not home

2) My extruder will not respond. I checked cables, motor, and the driver and they work fine. I wondering if there is something in marlin i need to define maybe.

I want to  mention I set my TMC2208 to 1v. I have no idea what is a good number

please i need help. maybe im missing something in my configuration files. greatly appreciate if someone can have a look over my files
[config files.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/files/6720997/config.files.zip)

**Comment by radek8** [comment]
Why do you have Endstop on the X axis defined in the opposite way to the Y axis?
#define X_MIN_ENDSTOP_INVERTING true  
#define Y_MIN_ENDSTOP_INVERTING false

If you use the same wired microswitch, it should be defined the same.

**Comment by radek8** [comment]
TMC2208 drivers are in STANDALONE mode.
I personally prefer UART mod.
You are using an old version of Marlin. I would recommend upgrading to the new version

**Comment by radek8** [comment]
Which means point 2 that you can't move the extruder. Does this mean that the fiber is not extruded during printing?

**Comment by radek8** [comment]
If you no longer have a problem, can you close the ticket?
