### ISSUE TITLE
SKR 1.3 working on USB but not working on AC.

### ISSUE THREAD

**Issue by StefanoV1989** [bigtreetech/BIGTREETECH-SKR-V1.3#537]
I updated my CR10 Mini from the standard board to a Bigtreetech SKR 1.3 and i installed TMC2208 in UART with a 5th extruder motor (and a mixing hotend ZSYong Mix),

I plug everything correctly and double checked. I uploaded the firmware.bin (became FIRMWARE.cur in the SD) and tried connecting with pronterface via USB cable with switch power on USB. 
Pronterface says "printer is online".

I then remove the USB cable, place the switch on AC Power and switch on the printer. Fan turned on and everything seems OK, but:  display is off and if i press the display button i get a "Beep",

What can i do? Is there a debug for SKR 1.3 to check if there is any conflict?

**Comment by radek8** [comment]
Do you have the switch in the correct position?
Did you check the fuses?

![image](https://user-images.githubusercontent.com/46979052/125358403-21055180-e369-11eb-968f-46e4e8b051c2.png)

**Comment by StefanoV1989** [comment]
> 
> 
> Do you have the switch in the correct position?
> Did you check the fuses?
> 
> ![image](https://user-images.githubusercontent.com/46979052/125358403-21055180-e369-11eb-968f-46e4e8b051c2.png)

Yes, switch OK and Fuse working. 

My Cr10-Mini has the double cable monitor as for CR10S (EXP 1 and EXP 2 plugs). I read online that i need to 180 degree rotate both cables on the SKR 1.3, is that true?

**Comment by StefanoV1989** [comment]
I rotated the EXP1 and EXP2 cable, now the display is on but blank, and the board started to do a long continuous beep and i can't recognize it anymore as COM port on my PC...
I don't know what to do now...

**Comment by radek8** [comment]
If the display worked, why did you rotate the connectors?
Return the connectors to their original position. There is a risk of damage to the electronics.
You write that the switch is OK. That's a funny answer.
In what position is it?
The correct position is this:

![image](https://user-images.githubusercontent.com/46979052/125520928-cacb2b91-9e02-473d-b97b-163cbed79457.png)

**Comment by radek8** [comment]
What display model do you use?
What display driver did you define in Marlin?

**Comment by StefanoV1989** [comment]
> 
> 
> What display model do you use?
> What display driver did you define in Marlin?

Display model is the CR10s display, in Marlin i tried REPRAP_DISCOUNT_FULL_GRAPHIC_LCD but also CR10_STOCKDISPLAY.
Both didn't work.

**Comment by radek8** [comment]
Send a photo of the connector connection

**Comment by StefanoV1989** [comment]
> 
> 
> Send a photo of the connector connection

![20210713_173758](https://user-images.githubusercontent.com/23081217/125583907-ca076656-4574-4cdf-8faf-3e093d4e280e.jpg)

**Comment by radek8** [comment]
use
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Comment by radek8** [comment]
You're right with the cables. In the photo, the cables are rotated 180 °
Connect them correctly.

**Comment by radek8** [comment]
![20210714_212901](https://user-images.githubusercontent.com/46979052/125681494-1fc7ea18-6239-4daa-8d2e-ff06116968ad.jpg)
![20210714_212605](https://user-images.githubusercontent.com/46979052/125681211-6ea233bd-e384-44a9-a2a0-d2aad0186c4b.jpg)

**Comment by StefanoV1989** [comment]
@radek8 I tried rotating 180° but the display switches on with really low contrast for 2 seconds and then off. If i press the encoder, it beeps and nothing else.
I tried to re-connect the display on the cr10mini board and it works properly, so i wonder if it's a board problem.
I ordered another display from Amazon (Reprap full graphic lcd), i will try with it when i will get it this Friday. If it doesn't work either, then i will know it's a board problem.

**Comment by radek8** [comment]
Did you use the correct driver?

#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

I bought a touch screen BTT TFT 35 E3 V3.0
I practically don't use Marlin mode anymore.

**Comment by StefanoV1989** [comment]
> 
> 
> Did you use the correct driver?
> 
> #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
> 
> I bought a touch screen BTT TFT 35 E3 V3.0
> I practically don't use Marlin mode anymore.

Sure i did.
Tomorrow i will receive the generic Reprap full graphic display from Amazon. If it doesn't work either, i decide i will upgrade everything to a SKR 1.4 Turbo + TFT35 v3.0 and that's it.
I payed SKR 1.3 just 17$ on Aliexpress from a random seller (not BTT), i wonder if there's some problem on it ... better if i buy everything from BTT page next time...

**Comment by radek8** [comment]
If you turn on SKR V1.3
without a display and you connect to a computer via USB, is your COM port mapped?

**Comment by radek8** [comment]
> 
> Sure i did.
> Tomorrow i will receive the generic Reprap full graphic display from Amazon. If it doesn't work either, i decide i will upgrade everything to a SKR 1.4 Turbo + TFT35 v3.0 and that's it.
> I payed SKR 1.3 just 17$ on Aliexpress from a random seller (not BTT), i wonder if there's some problem on it ... better if i buy everything from BTT page next time...

TFT35 E3 V3.0 is better for you. It is dimensionally compatible with the original Creality display.

**Comment by StefanoV1989** [comment]
> 
> 
> If you turn on SKR V1.3
> without a display and you connect to a computer via USB, is your COM port mapped?

Yes sure. and i can also move axis etc. i didn't try to print but i think i can normally print because everything seems OK.

**Comment by radek8** [comment]
So Marlin is running.

**Comment by StefanoV1989** [comment]
Ok, everything is working now with the new screen from Amazon.
I also got a problem with mizing extruder but i discover it was a Marlin 2.0.9 bug, i downgraded to Marlin 2.0.8.2 and everything is working now!

**Comment by radek8** [comment]
If you have resolved the issue, you can close the ticket.
