### ISSUE TITLE
FAN1 is still ON

### ISSUE THREAD

**Issue by seymon92** [bigtreetech/BIGTREETECH-SKR-V1.3#539]
Hello,
yesterday I installed 1.4 Turbo board, everything is working but FAN1 is still on. I have set E0 auto fan pin to P2_04 and temperature to 60, but it automaticly take on when printer starts.

#define E0_AUTO_FAN_PIN P2_04
#define EXTRUDER_AUTO_FAN_TEMPERATURE 60

Where could be problem?
Thank You

**Comment by seymon92** [comment]
My fault, I connected hot end cooling fan to FAN1 not to HE1.

**Comment by radek8** [comment]
If you no longer have a problem, can you close the ticket?
