### ISSUE TITLE
[SKR1.4 Turbo] Board seams dead. No USB, no Display

### ISSUE THREAD

**Issue by alabiana** [bigtreetech/BIGTREETECH-SKR-V1.3#555]
Hey Guys,

i just wanted to install my BLtouch (v3) today and updated the firmware for this with the relating changes to the configuration.h
But after placing the sdcard with the firmware.bin into the board it doesnt start anymore. I get no display signal an no uart connection (usb or tft).
The board still renames the firmware.bin to firmware.cur and even the old firmware.bin doesnt work.
Im working with platform.io and have an arduino uno here. Is there any way to unbrick the board or to activate debug or anything to see what is wrong?

**Comment by radek8** [comment]
If the bin file is renamed to cur. The SkR 1.4 board is running. The problem is in the configuration.

**Comment by JeffMedd** [comment]
@alabiana did you ever resolve this? same thing is happening to me at the moment.

**Comment by alabiana** [comment]
The file was not renamed. I tried with another sd card and Compiled the Firmware again. Then it works again.
