### ISSUE TITLE
cnc fan he1 port

### ISSUE THREAD

**Issue by Vilunki15** [bigtreetech/BIGTREETECH-SKR-V1.3#558]
Hi! Something blew up my skr 1.4t CNC fan MOSFET. I found I can use the he1 port for a CNC fan, but I don't have any idea how. I didn't find any fan port configurations from marlin. So, how I can use he1 port as a cnc fan?

**Comment by radek8** [comment]
In the file
Marlin \ src \ pins \ lpc1768 \ pins_BTT_SKR_common.h
rewrite the line
#define FAN_PIN P2_03
on
#define FAN_PIN P2_04

**Comment by Vilunki15** [comment]
> 

Thank you! It worked!
