### ISSUE TITLE
SKR 1.4 Turbo not visible on pc via usb

### ISSUE THREAD

**Issue by Navally** [bigtreetech/BIGTREETECH-SKR-V1.3#571]
Hi there!
I bought an SKR 1.4 Turbo to my Anet ET4+ and it worked perfectly but when i mount ESP-01S to that MB and flashed marlin with configuration Serial port 1: 3, Serial port 2: -1 then i cant connect it with my PC via USB cable. I tried to flash older configuration with Serial port 1: -1 and Serial port 2: 0 it still don't connect with PC.
Any idea where is the problem?
Thanks!

**Comment by radek8** [comment]
The way you configured it is fine.
option -1 activates the USB port
option 0 activates the serial port of the TFT connector
option 3 activates the serial port of the WIFI connector

Can you send the configuration files?

**Comment by Navally** [comment]
[Marlin.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/files/10528395/Marlin.zip)

**Comment by radek8** [comment]
The ports are defined correctly.
But why are you compiling an old version of Marlin?

**Comment by Navally** [comment]
I had this version, and latest from marlin github. On both versions is the same with USB connection.

**Comment by radek8** [comment]
I have the same board, + TFT display + ESP-01S
and the USB port works for me.

**Comment by radek8** [comment]
After connecting the printer to the PC, check whether you have a problem with the drivers on the PC

**Comment by Navally** [comment]
Drivers are ok, on second PC is the same.

**Comment by Navally** [comment]
Thanks for your time! I think there is a problem with chip lpc1769 and i contact with the seller and he send to me second MB.
