### ISSUE TITLE
MKS TFT32 Issue

### ISSUE THREAD

**Issue by Reddemon159** [bigtreetech/BIGTREETECH-SKR-V1.3#62]
I have an MKS TFT32 v3.0.3 hooked up to the SKR v1.3. It powers up loads up and everything. But the display doesn't receive any info from the board. Such as Temps. Touch commands are unresponsive. I have it plugged into the AUX 1 Slot. Is it not compatible with this control board?

**Comment by djtaotao** [comment]
How did you solve it?

**Comment by djtaotao** [comment]
> How did you solve it?

Nevermind. I have solved.
It was a baudrate mismatch, between MKS TFT35  and Marlin.

**Comment by edoluck90** [comment]
Please can you show a scheme to connect it ?  I have a mks tft32 v3 and a skr v1.4 turbo and I can’t connect because I don’t know how to wire it

**Comment by djtaotao** [comment]
Connect the 8 wire ribbon cable to aux 1 on skr.

**Comment by edoluck90** [comment]
![745EFE28-A37C-4D30-9631-81C0DF580C2C](https://user-images.githubusercontent.com/37956494/110483330-ea34db80-80e9-11eb-8050-1da1317a20f9.jpeg)
![93BCC0F1-2DB1-4E12-9F87-B61132D3FBBC](https://user-images.githubusercontent.com/37956494/110483355-ef922600-80e9-11eb-85d5-47cbe53f0fa0.jpeg)

How ? The exp 1 has 10 pin the mks tft32 8

**Comment by djtaotao** [comment]
I see only 8 pins on aux1.
![8](https://user-images.githubusercontent.com/16991258/110485311-2c631a80-80f4-11eb-9838-75c3fa9f7cc4.jpeg)

**Comment by edoluck90** [comment]
Ok but on skr v1.4 turbo you only have the tft port with 5 pin and the exp1 exp2 you have 10 pin

**Comment by djtaotao** [comment]
Ok, I didn't know that skr turbo don't have aux1. But has a 5 pin connector and you can use 4 of them: RX, TX, Gnd and Pwr (5V).
![SKR-V1 4-Turbo-pinout](https://user-images.githubusercontent.com/16991258/110487847-a4cadb00-80f6-11eb-82a3-13f88127731f.jpg)
