### ISSUE TITLE
Ender 3 with 2130's and BLTouch 3.0 - Z-axis doesnt go down, BLTouch doesnt work

### ISSUE THREAD

**Issue by JBrew13** [bigtreetech/BIGTREETECH-SKR-V1.3#71]
Everything EXCEPT the BLTouch works great. I can send the M280 commands and they all work fine. Self Test, probe down, etc. All work. When I Z-Home or G29, the probe will not deploy to actually probe the bed. I've gone through the Teaching Tech fixes videos and found a number of resources online. What changes should I try in the firmware?

**Comment by cronos45** [comment]
Did you solve your issue @JBrew13 ?

**Comment by nakedandjameson** [comment]
@JBrew13 Did you ever find a solution to this issue? I'm having the same problem.
