### ISSUE TITLE
TMC2130-SPI with wire

### ISSUE THREAD

**Issue by JohnnyTheOne** [bigtreetech/BIGTREETECH-SKR-V1.3#8]
How can I connect TMC2130-SPI with wire to SKR v1.3 like v1.1

**Comment by Msq001** [comment]
V1.3 SPI does not require as complex wiring as v1.1, The method of using tmc2130 SPI mode is shown in here. https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/Wiring%20diagram/SKR-V1.3-TMC2130-SPI-Mode.png 
And unless you don't use lcd,  you can wire to EXP-1 or EXP-2 like v1.1.

**Comment by zombu2** [comment]
did you ever figure out wth they talking about and how to get the 2130's going without blowing em to kingdom come?
