### ISSUE TITLE
Higher BAUDRATE 

### ISSUE THREAD

**Issue by CsepregiArtur** [bigtreetech/BIGTREETECH-SKR-V1.3#81]
Hello

What is the limit, or risk tto use higher BAUDRATE ?
insted of 115200 somthing higher wil cause me problems?

Thank you

**Comment by MasterDomino** [comment]
The baudrate cant damage your device, if you select a wrong baudrate you will just get jibberish, there's totally no risk, although you dont need to change the baudrate as 115200 should be totally enough.
