### ISSUE TITLE
Confirmation to connect serial...

### ISSUE THREAD

**Issue by CsepregiArtur** [bigtreetech/BIGTREETECH-SKR-V1.3#82]
Hello

I recive a Click to resume... message every time I start my printer, and i have a serial conected to it.
why this question is raised when connect serial?
Can you help me?

**Comment by carl1961** [comment]
Do you have power loss recovery enabled in firmware?

**Comment by CsepregiArtur** [comment]
@carl1961 no I don't have. I have a d1 mini conected to Aux-1 with ESP3D on it. When it is not conected evrithing boots up ok, when I conect it i recive this message "Click to resume..."

**Comment by carl1961** [comment]
Then it is your esp3d , maybe login to esp3d and check your settings

**Comment by CsepregiArtur** [comment]
nope  my problem was that I needed to enable the buffer in Marlin
