### ISSUE TITLE
5V UART are tolerant?

### ISSUE THREAD

**Issue by DimchikUA** [bigtreetech/BIGTREETECH-SKR-V1.3#9]
I use OctoPI and conect it to my board with USB TTL converter CP2102. Converter has 5v ttl logic level. Can I conected it to TFT or AUX-1 plug? Should I look for a converter with a 3.3V ttl level or I can use an existing one.

**Comment by Msq001** [comment]
> 5 V tolerant pad providing digital I/O functions (with TTL levels and hysteresis) and analog input. When configured as a ADC input,
digital section of the pad is disabled and the pin is not 5 V tolerant. This pin is pulled up to a voltage level of 2.3 V to 2.6 

in lpc1768 datasheet, AUX-1 is used for digital I/O, so it's 5V tolerant

**Comment by DimchikUA** [comment]
I confirm. I connected and it works.
